/* Generated by           cobc 3.2.0 */
/* Generated from         C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
/* Generated at           Sep 10 2025 08:56:18 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\msys64\mingw64\bin\cobc.exe -x -std=cobol85 -g -I ./copybooks -debug C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 10 2025 08:56:18"
#define  COB_MODULE_DATE		20250910
#define  COB_MODULE_TIME		85618

/* Global variables */
#include "cajero.c.h"

/* Function prototypes */

static int		cajero ();
static int		cajero_ (const int);
static void		cajero_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (cajero ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'cajero' */

/* ENTRY 'cajero' */

static int
cajero ()
{
  return cajero_ (0);
}

static int
cajero_ (const int entry)
{
  /* Program local variables */
  #include "cajero.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;
  module->frame_ptr = frame_stack;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d_0, &d_1);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  module->frame_ptr->section_name = "";
  module->frame_ptr->paragraph_name = "cajero";
  module->frame_ptr->module_stmt = 0x0010003D;
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 61        : Entry     cajero                  : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
  l_2:;
#line 61 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  ENTRY_CAJERO:	module->statement = STMT_ENTRY;
#line 113 "cajero.c"
  module->module_stmt = 0x0010003D;
  module->section_name = NULL;
  module->paragraph_name = NULL;

  /* Line: 61        : Paragraph MAIN-PROGRAM            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 61 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  PARAGRAPH_MAIN__PROGRAM_l_4:	module->statement = STMT_ENTRY;
#line 121 "cajero.c"
  module->paragraph_name = st_1;

  /* Line: 62        : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 62 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_MOVE;
#line 127 "cajero.c"
  module->module_stmt = 0x0010003E;
  *(b_14) = 78;

  /* Line: 63        : PERFORM            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 63 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_PERFORM;
#line 134 "cajero.c"
  module->module_stmt = 0x0010003F;
  for (;;)
  {
    /* Line: 63        : UNTIL              : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 63 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_UNTIL;
#line 141 "cajero.c"
    module->module_stmt = 0x0010003F;
    if (((int)(int)(*(b_14) - (unsigned char)'S') == 0))
      break;

    /* Line: 64        : PERFORM            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 64 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_PERFORM;
#line 149 "cajero.c"
    module->module_stmt = 0x00100040;
    /* PERFORM DISPLAY-MENU */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 5;
    frame_ptr->return_address_ptr = &&l_18;
    goto l_5;
    l_18:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;

    /* Line: 65        : PERFORM            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 65 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_PERFORM;
#line 172 "cajero.c"
    module->module_stmt = 0x00100041;
    /* PERFORM VALIDAR-PIN */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 6;
    frame_ptr->return_address_ptr = &&l_19;
    goto l_6;
    l_19:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;
  }

  /* Line: 67        : STOP RUN           : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 67 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_STOP_RUN;
#line 196 "cajero.c"
  module->module_stmt = 0x00100043;
  cob_stop_run (0);

  /* Line: 69        : Paragraph DISPLAY-MENU            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
  l_5:;
#line 69 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  PARAGRAPH_DISPLAY__MENU_l_5:	module->statement = STMT_ENTRY;
#line 204 "cajero.c"
  module->module_stmt = 0x00100045;
  module->paragraph_name = st_2;

  /* Line: 70        : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 70 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_DISPLAY;
#line 211 "cajero.c"
  module->module_stmt = 0x00100046;
  cob_display (0, 1, 1, &c_1);

  /* Line: 71        : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 71 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_DISPLAY;
#line 218 "cajero.c"
  module->module_stmt = 0x00100047;
  cob_display (0, 1, 1, &c_2);

  /* Line: 72        : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 72 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_DISPLAY;
#line 225 "cajero.c"
  module->module_stmt = 0x00100048;
  cob_display (0, 1, 1, &c_1);

  /* Line: 73        : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 73 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_DISPLAY;
#line 232 "cajero.c"
  module->module_stmt = 0x00100049;
  cob_display (0, 1, 1, &c_3);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address_ptr;

  /* Line: 75        : Paragraph VALIDAR-PIN             : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
  l_6:;
#line 75 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  PARAGRAPH_VALIDAR__PIN_l_6:	module->statement = STMT_ENTRY;
#line 244 "cajero.c"
  module->module_stmt = 0x0010004B;
  module->paragraph_name = st_3;

  /* Line: 76        : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 76 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_MOVE;
#line 251 "cajero.c"
  module->module_stmt = 0x0010004C;
  *(b_10) = 78;

  /* Line: 77        : PERFORM            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 77 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_PERFORM;
#line 258 "cajero.c"
  module->module_stmt = 0x0010004D;
  for (;;)
  {
    /* Line: 77        : UNTIL              : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 77 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_UNTIL;
#line 265 "cajero.c"
    module->module_stmt = 0x0010004D;
    if (((int)(int)(*(b_10) - (unsigned char)'S') == 0))
      break;

    /* Line: 78        : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 78 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_DISPLAY;
#line 273 "cajero.c"
    module->module_stmt = 0x0010004E;
    cob_display (0, 1, 1, &c_4);

    /* Line: 79        : ACCEPT             : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 79 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_ACCEPT;
#line 280 "cajero.c"
    module->module_stmt = 0x0010004F;
    cob_accept (&f_8);

    /* Line: 81        : IF                 : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 81 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_IF;
#line 287 "cajero.c"
    module->module_stmt = 0x00100051;
    if ((cob_is_numeric (&f_8) && 
        1))
    {

      /* Line: 82        : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 82 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_MOVE;
#line 296 "cajero.c"
      module->module_stmt = 0x00100052;
      cob_move (&f_8, &f_9);

      /* Line: 83        : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 83 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_MOVE;
#line 303 "cajero.c"
      module->module_stmt = 0x00100053;
      *(b_10) = 83;

      /* Line: 84        : PERFORM            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 84 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_PERFORM;
#line 310 "cajero.c"
      module->module_stmt = 0x00100054;
      /* PERFORM MENU-OPERACIONES */
      frame_ptr++;
      frame_ptr->module_stmt = module->module_stmt;
      frame_ptr->section_name = module->section_name;
      frame_ptr->paragraph_name = module->paragraph_name;
      module->frame_ptr = frame_ptr;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 7;
      frame_ptr->return_address_ptr = &&l_20;
      goto l_7;
      l_20:
      frame_ptr--;
      module->module_stmt = module->frame_ptr->module_stmt;
      module->section_name = module->frame_ptr->section_name;
      module->paragraph_name = module->frame_ptr->paragraph_name;
      module->frame_ptr = frame_ptr;
    }
    else
    {
      /* ELSE */

      /* Line: 86        : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 86 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_DISPLAY;
#line 337 "cajero.c"
      module->module_stmt = 0x00100056;
      cob_display (0, 1, 1, &c_5);
    }
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 90        : Paragraph MENU-OPERACIONES        : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
  l_7:;
#line 90 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  PARAGRAPH_MENU__OPERACIONES_l_7:	module->statement = STMT_ENTRY;
#line 351 "cajero.c"
  module->module_stmt = 0x0010005A;
  module->paragraph_name = st_4;

  /* Line: 91        : CALL               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 91 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_CALL;
#line 358 "cajero.c"
  module->module_stmt = 0x0010005B;
  cob_procedure_params[0] = (cob_field *)&c_6;
  cob_glob_ptr->cob_call_params = 1;
  cob_glob_ptr->cob_stmt_exception = 0;
  (void)cob_sys_system ((cob_u8_ptr)"CLS");

  /* Line: 92        : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 92 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_DISPLAY;
#line 368 "cajero.c"
  module->module_stmt = 0x0010005C;
  cob_display (0, 1, 1, &c_7);

  /* Line: 93        : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 93 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_DISPLAY;
#line 375 "cajero.c"
  module->module_stmt = 0x0010005D;
  cob_display (0, 1, 1, &c_8);

  /* Line: 94        : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 94 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_DISPLAY;
#line 382 "cajero.c"
  module->module_stmt = 0x0010005E;
  cob_display (0, 1, 1, &c_9);

  /* Line: 95        : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 95 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_DISPLAY;
#line 389 "cajero.c"
  module->module_stmt = 0x0010005F;
  cob_display (0, 1, 1, &c_10);

  /* Line: 96        : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 96 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_DISPLAY;
#line 396 "cajero.c"
  module->module_stmt = 0x00100060;
  cob_display (0, 1, 1, &c_11);

  /* Line: 97        : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 97 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_DISPLAY;
#line 403 "cajero.c"
  module->module_stmt = 0x00100061;
  cob_display (0, 1, 1, &c_12);

  /* Line: 98        : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 98 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_DISPLAY;
#line 410 "cajero.c"
  module->module_stmt = 0x00100062;
  cob_display (0, 1, 1, &c_13);

  /* Line: 99        : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 99 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_DISPLAY;
#line 417 "cajero.c"
  module->module_stmt = 0x00100063;
  cob_display (0, 1, 1, &c_14);

  /* Line: 100       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 100 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_DISPLAY;
#line 424 "cajero.c"
  module->module_stmt = 0x00100064;
  cob_display (0, 0, 1, &c_15);

  /* Line: 101       : ACCEPT             : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 101 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_ACCEPT;
#line 431 "cajero.c"
  module->module_stmt = 0x00100065;
  cob_accept (&f_1);

  /* Line: 103       : EVALUATE           : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 103 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_EVALUATE;
#line 438 "cajero.c"
  module->module_stmt = 0x00100067;

  /* Line: 104       : WHEN               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 104 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_WHEN;
#line 444 "cajero.c"
  module->module_stmt = 0x00100068;

  if (((int)cob_cmp_numdisp (b_1, 1, 1LL, 0) == 0))
  {

    /* Line: 104       : PERFORM            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 104 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_PERFORM;
#line 453 "cajero.c"
    /* PERFORM MENU-SALDO */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 9;
    frame_ptr->return_address_ptr = &&l_21;
    goto l_9;
    l_21:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;
    goto l_8;
  }

  /* Line: 105       : WHEN               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 105 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_WHEN;
#line 477 "cajero.c"
  module->module_stmt = 0x00100069;

  if (((int)cob_cmp_numdisp (b_1, 1, 2LL, 0) == 0))
  {

    /* Line: 105       : PERFORM            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 105 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_PERFORM;
#line 486 "cajero.c"
    /* PERFORM MENU-TRANSFERENCIA */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 11;
    frame_ptr->return_address_ptr = &&l_22;
    goto l_11;
    l_22:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;
    goto l_8;
  }

  /* Line: 106       : WHEN               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 106 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_WHEN;
#line 510 "cajero.c"
  module->module_stmt = 0x0010006A;

  if (((int)cob_cmp_numdisp (b_1, 1, 3LL, 0) == 0))
  {

    /* Line: 106       : PERFORM            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 106 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_PERFORM;
#line 519 "cajero.c"
    /* PERFORM MENU-DEPOSITO */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 12;
    frame_ptr->return_address_ptr = &&l_23;
    goto l_12;
    l_23:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;
    goto l_8;
  }

  /* Line: 107       : WHEN               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 107 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_WHEN;
#line 543 "cajero.c"
  module->module_stmt = 0x0010006B;

  if (((int)cob_cmp_numdisp (b_1, 1, 4LL, 0) == 0))
  {

    /* Line: 107       : PERFORM            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 107 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_PERFORM;
#line 552 "cajero.c"
    /* PERFORM MENU-EXTRACCION */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 14;
    frame_ptr->return_address_ptr = &&l_24;
    goto l_14;
    l_24:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;
    goto l_8;
  }

  /* Line: 108       : WHEN               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 108 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_WHEN;
#line 576 "cajero.c"
  module->module_stmt = 0x0010006C;

  if (((int)cob_cmp_numdisp (b_1, 1, 5LL, 0) == 0))
  {

    /* Line: 108       : PERFORM            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 108 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_PERFORM;
#line 585 "cajero.c"
    /* PERFORM MENU-ULT-MOVIMIENTOS */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 16;
    frame_ptr->return_address_ptr = &&l_25;
    goto l_16;
    l_25:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;
    goto l_8;
  }

  /* Line: 109       : WHEN               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 109 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_WHEN;
#line 609 "cajero.c"
  module->module_stmt = 0x0010006D;

  if (((int)cob_cmp_numdisp (b_1, 1, 6LL, 0) == 0))
  {

    /* Line: 109       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 109 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_MOVE;
#line 618 "cajero.c"
    *(b_14) = 78;
    goto l_8;
  }

  /* WHEN OTHER */

  /* Line: 110       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 110 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_DISPLAY;
#line 628 "cajero.c"
  module->module_stmt = 0x0010006E;
  cob_display (0, 1, 1, &c_16);

  /* End EVALUATE */
  l_8:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 113       : Paragraph MENU-SALDO              : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
  l_9:;
#line 113 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  PARAGRAPH_MENU__SALDO_l_9:	module->statement = STMT_ENTRY;
#line 643 "cajero.c"
  module->module_stmt = 0x00100071;
  module->paragraph_name = st_5;

  /* Line: 114       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 114 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_MOVE;
#line 650 "cajero.c"
  module->module_stmt = 0x00100072;
  memset (b_21, 48, 9);

  /* Line: 115       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 115 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_MOVE;
#line 657 "cajero.c"
  module->module_stmt = 0x00100073;
  cob_check_numeric (&f_15, "WS-SALDO");
  cob_move (&f_15, &f_16);

  /* Line: 116       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 116 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_DISPLAY;
#line 665 "cajero.c"
  module->module_stmt = 0x00100074;
  cob_display (0, 1, 3, &c_17, &c_18, &f_16);

  /* Line: 117       : PERFORM            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 117 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_PERFORM;
#line 672 "cajero.c"
  module->module_stmt = 0x00100075;
  for (;;)
  {
    /* Line: 117       : UNTIL              : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 117 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_UNTIL;
#line 679 "cajero.c"
    module->module_stmt = 0x00100075;
    if ((((int)cob_cmp_numdisp (b_21, 9, 1LL, 0) == 0) || 
        ((int)cob_cmp_numdisp (b_21, 9, 2LL, 0) == 0)))
      break;

    /* Line: 118       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 118 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_DISPLAY;
#line 688 "cajero.c"
    module->module_stmt = 0x00100076;
    cob_display (0, 1, 1, &c_19);

    /* Line: 119       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 119 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_DISPLAY;
#line 695 "cajero.c"
    module->module_stmt = 0x00100077;
    cob_display (0, 1, 1, &c_20);

    /* Line: 120       : ACCEPT             : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 120 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_ACCEPT;
#line 702 "cajero.c"
    module->module_stmt = 0x00100078;
    cob_accept (&f_21);

    /* Line: 122       : EVALUATE           : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 122 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_EVALUATE;
#line 709 "cajero.c"
    module->module_stmt = 0x0010007A;

    /* Line: 123       : WHEN               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 123 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_WHEN;
#line 715 "cajero.c"
    module->module_stmt = 0x0010007B;

    if (((int)cob_cmp_numdisp (b_21, 9, 1LL, 0) == 0))
    {

      /* Line: 124       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 124 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_DISPLAY;
#line 724 "cajero.c"
      module->module_stmt = 0x0010007C;
      cob_display (0, 1, 1, &c_21);

      /* Line: 125       : ACCEPT             : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 125 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_ACCEPT;
#line 731 "cajero.c"
      module->module_stmt = 0x0010007D;
      cob_accept (NULL);

      /* Line: 126       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 126 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_MOVE;
#line 738 "cajero.c"
      module->module_stmt = 0x0010007E;
      memcpy (b_21, "000000002", 9);
      goto l_10;
    }

    /* Line: 127       : WHEN               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 127 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_WHEN;
#line 747 "cajero.c"
    module->module_stmt = 0x0010007F;

    if (((int)cob_cmp_numdisp (b_21, 9, 2LL, 0) == 0))
    {

      /* Line: 128       : CONTINUE           : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 128 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_CONTINUE;
#line 756 "cajero.c"
      module->module_stmt = 0x00100080;
      ;
      goto l_10;
    }

    /* WHEN OTHER */

    /* Line: 130       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 130 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_DISPLAY;
#line 767 "cajero.c"
    module->module_stmt = 0x00100082;
    cob_display (0, 1, 1, &c_16);

    /* Line: 131       : ACCEPT             : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 131 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_ACCEPT;
#line 774 "cajero.c"
    module->module_stmt = 0x00100083;
    cob_accept (NULL);

    /* End EVALUATE */
    l_10:;
  }

  /* Line: 135       : IF                 : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 135 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_IF;
#line 785 "cajero.c"
  module->module_stmt = 0x00100087;
  if (((int)cob_cmp_numdisp (b_21, 9, 2LL, 0) == 0))
  {

    /* Line: 136       : PERFORM            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 136 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_PERFORM;
#line 793 "cajero.c"
    module->module_stmt = 0x00100088;
    /* PERFORM MENU-OPERACIONES */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_26;
    goto l_7;
    l_26:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 9)
    goto *frame_ptr->return_address_ptr;

  /* Line: 139       : Paragraph MENU-TRANSFERENCIA      : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
  l_11:;
#line 139 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  PARAGRAPH_MENU__TRANSFERENCIA_l_11:	module->statement = STMT_ENTRY;
#line 822 "cajero.c"
  module->module_stmt = 0x0010008B;
  module->paragraph_name = st_6;

  /* Line: 140       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 140 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_DISPLAY;
#line 829 "cajero.c"
  module->module_stmt = 0x0010008C;
  cob_display (0, 1, 1, &c_22);

  /* Line: 141       : ACCEPT             : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 141 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_ACCEPT;
#line 836 "cajero.c"
  module->module_stmt = 0x0010008D;
  cob_accept (&f_22);

  /* Line: 142       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 142 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_DISPLAY;
#line 843 "cajero.c"
  module->module_stmt = 0x0010008E;
  cob_display (0, 1, 1, &c_23);

  /* Line: 143       : ACCEPT             : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 143 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_ACCEPT;
#line 850 "cajero.c"
  module->module_stmt = 0x0010008F;
  cob_accept (&f_23);

  /* Line: 144       : IF                 : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 144 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_IF;
#line 857 "cajero.c"
  module->module_stmt = 0x00100090;
  if (((int)cob_cmp_numdisp (b_23, 9, cob_get_llint (&f_15), 0) > 0))
  {

    /* Line: 145       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 145 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_DISPLAY;
#line 865 "cajero.c"
    module->module_stmt = 0x00100091;
    cob_display (0, 1, 1, &c_24);

    /* Line: 146       : ACCEPT             : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 146 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_ACCEPT;
#line 872 "cajero.c"
    module->module_stmt = 0x00100092;
    cob_accept (NULL);

    /* Line: 147       : PERFORM            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 147 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_PERFORM;
#line 879 "cajero.c"
    module->module_stmt = 0x00100093;
    /* PERFORM MENU-OPERACIONES */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_27;
    goto l_7;
    l_27:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;
  }
  else
  {
    /* ELSE */

    /* Line: 149       : SUBTRACT           : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 149 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_SUBTRACT;
#line 906 "cajero.c"
    module->module_stmt = 0x00100095;
    cob_check_numeric (&f_23, "WS-MONTO-TRANSF");
    cob_check_numeric (&f_15, "WS-SALDO");
    cob_sub_int (&f_15, cob_get_numdisp (b_23, 9), 0);

    /* Line: 150       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 150 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_MOVE;
#line 915 "cajero.c"
    module->module_stmt = 0x00100096;
    cob_check_numeric (&f_15, "WS-SALDO");
    cob_move (&f_15, &f_16);

    /* Line: 151       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 151 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_MOVE;
#line 923 "cajero.c"
    module->module_stmt = 0x00100097;
    cob_check_numeric (&f_23, "WS-MONTO-TRANSF");
    cob_move (&f_23, &f_24);

    /* Line: 152       : IF                 : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 152 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_IF;
#line 931 "cajero.c"
    module->module_stmt = 0x00100098;
    if (((int)cob_cmp_numdisp (b_33, 1, 5LL, 0) >= 0))
    {

      /* Line: 153       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 153 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_MOVE;
#line 939 "cajero.c"
      module->module_stmt = 0x00100099;
      *(b_33) = 48;
    }

    /* Line: 155       : ADD                : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 155 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_ADD;
#line 947 "cajero.c"
    module->module_stmt = 0x0010009B;
    cob_check_numeric (&f_33, "WS-INDICE-MOV");
    cob_add_int (&f_33, 1, 0);

    /* Line: 156       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 156 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_MOVE;
#line 955 "cajero.c"
    module->module_stmt = 0x0010009C;
    cob_check_subscript (cob_get_numdisp (b_33, 1), 5, "WS-MOV-TIPO", 0);
    memcpy (b_26 + 37LL * ((cob_s64_t)(cob_get_numdisp (b_33, 1)) - 1), "Transferencia       ", 20);

    /* Line: 157       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 157 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_MOVE;
#line 963 "cajero.c"
    module->module_stmt = 0x0010009D;
    cob_check_numeric (&f_23, "WS-MONTO-TRANSF");
    cob_check_subscript (cob_get_numdisp (b_33, 1), 5, "WS-MOV-MONTO", 0);
    memcpy (b_26 + 20 + 37LL * ((cob_s64_t)(cob_get_numdisp (b_33, 1)) - 1), b_23, 9);

    /* Line: 158       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 158 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_DISPLAY;
#line 972 "cajero.c"
    module->module_stmt = 0x0010009E;
    cob_display (0, 1, 2, &c_25, &f_24);

    /* Line: 159       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 159 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_DISPLAY;
#line 979 "cajero.c"
    module->module_stmt = 0x0010009F;
    cob_display (0, 1, 2, &c_26, &f_16);

    /* Line: 160       : ACCEPT             : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 160 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_ACCEPT;
#line 986 "cajero.c"
    module->module_stmt = 0x001000A0;
    cob_accept (NULL);

    /* Line: 161       : PERFORM            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 161 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_PERFORM;
#line 993 "cajero.c"
    module->module_stmt = 0x001000A1;
    /* PERFORM MENU-OPERACIONES */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_28;
    goto l_7;
    l_28:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 11)
    goto *frame_ptr->return_address_ptr;

  /* Line: 164       : Paragraph MENU-DEPOSITO           : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
  l_12:;
#line 164 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  PARAGRAPH_MENU__DEPOSITO_l_12:	module->statement = STMT_ENTRY;
#line 1022 "cajero.c"
  module->module_stmt = 0x001000A4;
  module->paragraph_name = st_7;

  /* Line: 165       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 165 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_MOVE;
#line 1029 "cajero.c"
  module->module_stmt = 0x001000A5;
  *(b_13) = 48;

  /* Line: 166       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 166 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_DISPLAY;
#line 1036 "cajero.c"
  module->module_stmt = 0x001000A6;
  cob_display (0, 1, 1, &c_27);

  /* Line: 167       : ACCEPT             : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 167 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_ACCEPT;
#line 1043 "cajero.c"
  module->module_stmt = 0x001000A7;
  cob_accept (&f_12);

  /* Line: 168       : PERFORM            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 168 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_PERFORM;
#line 1050 "cajero.c"
  module->module_stmt = 0x001000A8;
  for (;;)
  {
    /* Line: 168       : UNTIL              : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 168 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_UNTIL;
#line 1057 "cajero.c"
    module->module_stmt = 0x001000A8;
    if ((((int)cob_cmp_numdisp (b_13, 1, 1LL, 0) == 0) || 
        ((int)cob_cmp_numdisp (b_13, 1, 2LL, 0) == 0)))
      break;

    /* Line: 169       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 169 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_DISPLAY;
#line 1066 "cajero.c"
    module->module_stmt = 0x001000A9;
    cob_display (0, 1, 1, &c_28);

    /* Line: 170       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 170 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_DISPLAY;
#line 1073 "cajero.c"
    module->module_stmt = 0x001000AA;
    cob_display (0, 1, 1, &c_29);

    /* Line: 171       : ACCEPT             : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 171 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_ACCEPT;
#line 1080 "cajero.c"
    module->module_stmt = 0x001000AB;
    cob_accept (&f_13);

    /* Line: 173       : EVALUATE           : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 173 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_EVALUATE;
#line 1087 "cajero.c"
    module->module_stmt = 0x001000AD;

    /* Line: 174       : WHEN               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 174 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_WHEN;
#line 1093 "cajero.c"
    module->module_stmt = 0x001000AE;

    if (((int)cob_cmp_numdisp (b_13, 1, 1LL, 0) == 0))
    {

      /* Line: 175       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 175 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_MOVE;
#line 1102 "cajero.c"
      module->module_stmt = 0x001000AF;
      cob_check_numeric (&f_12, "WS-MONTO");
      cob_move (&f_12, &f_11);

      /* Line: 176       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 176 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_DISPLAY;
#line 1110 "cajero.c"
      module->module_stmt = 0x001000B0;
      cob_display (0, 1, 2, &c_30, &f_11);

      /* Line: 177       : COMPUTE            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 177 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_COMPUTE;
#line 1117 "cajero.c"
      module->module_stmt = 0x001000B1;
      cob_check_numeric (&f_12, "WS-MONTO");
      cob_decimal_set_field (d_0, &f_12);
      cob_check_numeric (&f_15, "WS-SALDO");
      cob_decimal_set_field (d_1, &f_15);
      cob_decimal_add (d_0, d_1);
      cob_decimal_get_field (d_0, &f_15, 0);

      /* Line: 178       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 178 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_MOVE;
#line 1129 "cajero.c"
      module->module_stmt = 0x001000B2;
      cob_check_numeric (&f_15, "WS-SALDO");
      cob_move (&f_15, &f_16);

      /* Line: 180       : IF                 : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 180 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_IF;
#line 1137 "cajero.c"
      module->module_stmt = 0x001000B4;
      if (((int)cob_cmp_numdisp (b_33, 1, 5LL, 0) >= 0))
      {

        /* Line: 181       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 181 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
        module->statement = STMT_MOVE;
#line 1145 "cajero.c"
        module->module_stmt = 0x001000B5;
        *(b_33) = 48;
      }

      /* Line: 183       : ADD                : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 183 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_ADD;
#line 1153 "cajero.c"
      module->module_stmt = 0x001000B7;
      cob_check_numeric (&f_33, "WS-INDICE-MOV");
      cob_add_int (&f_33, 1, 0);

      /* Line: 184       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 184 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_MOVE;
#line 1161 "cajero.c"
      module->module_stmt = 0x001000B8;
      cob_check_subscript (cob_get_numdisp (b_33, 1), 5, "WS-MOV-TIPO", 0);
      memcpy (b_26 + 37LL * ((cob_s64_t)(cob_get_numdisp (b_33, 1)) - 1), "Deposito            ", 20);

      /* Line: 185       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 185 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_MOVE;
#line 1169 "cajero.c"
      module->module_stmt = 0x001000B9;
      cob_check_numeric (&f_12, "WS-MONTO");
      cob_check_subscript (cob_get_numdisp (b_33, 1), 5, "WS-MOV-MONTO", 0);
      cob_move (&f_12, COB_SET_FLD (f0, 9, b_26 + 20 + 37LL * ((cob_s64_t)(cob_get_numdisp (b_33, 1)) - 1), &a_7));

      /* Line: 186       : ACCEPT             : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 186 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_ACCEPT;
#line 1178 "cajero.c"
      module->module_stmt = 0x001000BA;
      cob_accept (NULL);

      /* Line: 187       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 187 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_MOVE;
#line 1185 "cajero.c"
      module->module_stmt = 0x001000BB;
      *(b_13) = 50;
      goto l_13;
    }

    /* Line: 188       : WHEN               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 188 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_WHEN;
#line 1194 "cajero.c"
    module->module_stmt = 0x001000BC;

    if (((int)cob_cmp_numdisp (b_13, 1, 2LL, 0) == 0))
    {

      /* Line: 189       : CONTINUE           : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 189 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_CONTINUE;
#line 1203 "cajero.c"
      module->module_stmt = 0x001000BD;
      ;
      goto l_13;
    }

    /* WHEN OTHER */

    /* Line: 191       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 191 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_DISPLAY;
#line 1214 "cajero.c"
    module->module_stmt = 0x001000BF;
    cob_display (0, 1, 1, &c_16);

    /* Line: 192       : ACCEPT             : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 192 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_ACCEPT;
#line 1221 "cajero.c"
    module->module_stmt = 0x001000C0;
    cob_accept (NULL);

    /* End EVALUATE */
    l_13:;
  }

  /* Line: 197       : IF                 : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 197 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_IF;
#line 1232 "cajero.c"
  module->module_stmt = 0x001000C5;
  if (((int)cob_cmp_numdisp (b_13, 1, 2LL, 0) == 0))
  {

    /* Line: 198       : PERFORM            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 198 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_PERFORM;
#line 1240 "cajero.c"
    module->module_stmt = 0x001000C6;
    /* PERFORM MENU-OPERACIONES */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_29;
    goto l_7;
    l_29:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 12)
    goto *frame_ptr->return_address_ptr;

  /* Line: 201       : Paragraph MENU-EXTRACCION         : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
  l_14:;
#line 201 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  PARAGRAPH_MENU__EXTRACCION_l_14:	module->statement = STMT_ENTRY;
#line 1269 "cajero.c"
  module->module_stmt = 0x001000C9;
  module->paragraph_name = st_8;

  /* Line: 202       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 202 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_MOVE;
#line 1276 "cajero.c"
  module->module_stmt = 0x001000CA;
  *(b_19) = 48;

  /* Line: 203       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 203 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_MOVE;
#line 1283 "cajero.c"
  module->module_stmt = 0x001000CB;
  memset (b_17, 48, 9);

  /* Line: 205       : PERFORM            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 205 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_PERFORM;
#line 1290 "cajero.c"
  module->module_stmt = 0x001000CD;
  for (;;)
  {
    /* Line: 205       : UNTIL              : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 205 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_UNTIL;
#line 1297 "cajero.c"
    module->module_stmt = 0x001000CD;
    if (((((int)cob_cmp_numdisp (b_17, 9, 0LL, 0) > 0) && 
        ((int)cob_cmp_numdisp (b_17, 9, cob_get_llint (&f_15), 0) <= 0)) && 
        ((int)cob_cmp_numdisp (b_17, 9, cob_get_llint (&f_20), 0) <= 0)))
      break;

    /* Line: 209       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 209 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_MOVE;
#line 1307 "cajero.c"
    module->module_stmt = 0x001000D1;
    cob_check_numeric (&f_15, "WS-SALDO");
    cob_move (&f_15, &f_16);

    /* Line: 210       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 210 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_DISPLAY;
#line 1315 "cajero.c"
    module->module_stmt = 0x001000D2;
    cob_display (0, 1, 2, &c_31, &f_16);

    /* Line: 211       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 211 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_DISPLAY;
#line 1322 "cajero.c"
    module->module_stmt = 0x001000D3;
    cob_display (0, 1, 1, &c_32);

    /* Line: 212       : ACCEPT             : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 212 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_ACCEPT;
#line 1329 "cajero.c"
    module->module_stmt = 0x001000D4;
    cob_accept (&f_17);

    /* Line: 214       : IF                 : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 214 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_IF;
#line 1336 "cajero.c"
    module->module_stmt = 0x001000D6;
    if (((int)cob_cmp_numdisp (b_17, 9, cob_get_llint (&f_15), 0) > 0))
    {

      /* Line: 215       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 215 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_DISPLAY;
#line 1344 "cajero.c"
      module->module_stmt = 0x001000D7;
      cob_display (0, 1, 1, &c_33);

      /* Line: 216       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 216 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_MOVE;
#line 1351 "cajero.c"
      module->module_stmt = 0x001000D8;
      memset (b_17, 48, 9);

      /* Line: 217       : ACCEPT             : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 217 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_ACCEPT;
#line 1358 "cajero.c"
      module->module_stmt = 0x001000D9;
      cob_accept (NULL);
    }
    else
    {
      /* ELSE */

      /* Line: 219       : IF                 : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 219 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_IF;
#line 1369 "cajero.c"
      module->module_stmt = 0x001000DB;
      if (((int)cob_cmp_numdisp (b_17, 9, cob_get_llint (&f_20), 0) > 0))
      {

        /* Line: 220       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 220 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
        module->statement = STMT_DISPLAY;
#line 1377 "cajero.c"
        module->module_stmt = 0x001000DC;
        cob_display (0, 1, 3, &c_34, &f_20, &c_35);

        /* Line: 221       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 221 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
        module->statement = STMT_DISPLAY;
#line 1384 "cajero.c"
        module->module_stmt = 0x001000DD;
        cob_display (0, 1, 1, &c_36);

        /* Line: 222       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 222 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
        module->statement = STMT_MOVE;
#line 1391 "cajero.c"
        module->module_stmt = 0x001000DE;
        memset (b_17, 48, 9);

        /* Line: 223       : ACCEPT             : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 223 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
        module->statement = STMT_ACCEPT;
#line 1398 "cajero.c"
        module->module_stmt = 0x001000DF;
        cob_accept (NULL);
      }
    }
  }

  /* Line: 228       : PERFORM            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 228 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_PERFORM;
#line 1408 "cajero.c"
  module->module_stmt = 0x001000E4;
  for (;;)
  {
    /* Line: 228       : UNTIL              : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 228 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_UNTIL;
#line 1415 "cajero.c"
    module->module_stmt = 0x001000E4;
    if ((((int)cob_cmp_numdisp (b_19, 1, 1LL, 0) == 0) || 
        ((int)cob_cmp_numdisp (b_19, 1, 2LL, 0) == 0)))
      break;

    /* Line: 229       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 229 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_DISPLAY;
#line 1424 "cajero.c"
    module->module_stmt = 0x001000E5;
    cob_display (0, 1, 1, &c_37);

    /* Line: 230       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 230 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_DISPLAY;
#line 1431 "cajero.c"
    module->module_stmt = 0x001000E6;
    cob_display (0, 1, 1, &c_29);

    /* Line: 231       : ACCEPT             : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 231 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_ACCEPT;
#line 1438 "cajero.c"
    module->module_stmt = 0x001000E7;
    cob_accept (&f_19);

    /* Line: 233       : EVALUATE           : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 233 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_EVALUATE;
#line 1445 "cajero.c"
    module->module_stmt = 0x001000E9;

    /* Line: 234       : WHEN               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 234 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_WHEN;
#line 1451 "cajero.c"
    module->module_stmt = 0x001000EA;

    if (((int)cob_cmp_numdisp (b_19, 1, 1LL, 0) == 0))
    {

      /* Line: 235       : COMPUTE            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 235 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_COMPUTE;
#line 1460 "cajero.c"
      module->module_stmt = 0x001000EB;
      cob_check_numeric (&f_15, "WS-SALDO");
      cob_decimal_set_field (d_0, &f_15);
      cob_check_numeric (&f_17, "WS-MONTO-EXT");
      cob_decimal_set_field (d_1, &f_17);
      cob_decimal_sub (d_0, d_1);
      cob_decimal_get_field (d_0, &f_15, 0);

      /* Line: 236       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 236 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_MOVE;
#line 1472 "cajero.c"
      module->module_stmt = 0x001000EC;
      cob_check_numeric (&f_15, "WS-SALDO");
      cob_move (&f_15, &f_16);

      /* Line: 237       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 237 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_MOVE;
#line 1480 "cajero.c"
      module->module_stmt = 0x001000ED;
      cob_check_numeric (&f_17, "WS-MONTO-EXT");
      cob_move (&f_17, &f_18);

      /* Line: 238       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 238 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_DISPLAY;
#line 1488 "cajero.c"
      module->module_stmt = 0x001000EE;
      cob_display (0, 1, 2, &c_38, &f_18);

      /* Line: 239       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 239 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_DISPLAY;
#line 1495 "cajero.c"
      module->module_stmt = 0x001000EF;
      cob_display (0, 1, 1, &f_33);

      /* Line: 240       : IF                 : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 240 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_IF;
#line 1502 "cajero.c"
      module->module_stmt = 0x001000F0;
      if (((int)cob_cmp_numdisp (b_33, 1, 5LL, 0) >= 0))
      {

        /* Line: 241       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 241 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
        module->statement = STMT_MOVE;
#line 1510 "cajero.c"
        module->module_stmt = 0x001000F1;
        *(b_33) = 48;
      }

      /* Line: 243       : ADD                : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 243 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_ADD;
#line 1518 "cajero.c"
      module->module_stmt = 0x001000F3;
      cob_check_numeric (&f_33, "WS-INDICE-MOV");
      cob_add_int (&f_33, 1, 0);

      /* Line: 244       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 244 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_MOVE;
#line 1526 "cajero.c"
      module->module_stmt = 0x001000F4;
      cob_check_subscript (cob_get_numdisp (b_33, 1), 5, "WS-MOV-TIPO", 0);
      memcpy (b_26 + 37LL * ((cob_s64_t)(cob_get_numdisp (b_33, 1)) - 1), "Extraccion          ", 20);

      /* Line: 245       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 245 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_MOVE;
#line 1534 "cajero.c"
      module->module_stmt = 0x001000F5;
      cob_check_numeric (&f_17, "WS-MONTO-EXT");
      cob_check_subscript (cob_get_numdisp (b_33, 1), 5, "WS-MOV-MONTO", 0);
      memcpy (b_26 + 20 + 37LL * ((cob_s64_t)(cob_get_numdisp (b_33, 1)) - 1), b_17, 9);

      /* Line: 246       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 246 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_DISPLAY;
#line 1543 "cajero.c"
      module->module_stmt = 0x001000F6;
      cob_display (0, 1, 2, &c_39, &f_16);

      /* Line: 247       : ACCEPT             : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 247 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_ACCEPT;
#line 1550 "cajero.c"
      module->module_stmt = 0x001000F7;
      cob_accept (NULL);

      /* Line: 248       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 248 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_MOVE;
#line 1557 "cajero.c"
      module->module_stmt = 0x001000F8;
      *(b_19) = 50;
      goto l_15;
    }

    /* Line: 249       : WHEN               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 249 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_WHEN;
#line 1566 "cajero.c"
    module->module_stmt = 0x001000F9;

    if (((int)cob_cmp_numdisp (b_19, 1, 2LL, 0) == 0))
    {

      /* Line: 250       : CONTINUE           : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 250 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_CONTINUE;
#line 1575 "cajero.c"
      module->module_stmt = 0x001000FA;
      ;
      goto l_15;
    }

    /* WHEN OTHER */

    /* Line: 252       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 252 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_DISPLAY;
#line 1586 "cajero.c"
    module->module_stmt = 0x001000FC;
    cob_display (0, 1, 1, &c_40);

    /* Line: 253       : ACCEPT             : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 253 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_ACCEPT;
#line 1593 "cajero.c"
    module->module_stmt = 0x001000FD;
    cob_accept (NULL);

    /* End EVALUATE */
    l_15:;
  }

  /* Line: 256       : IF                 : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 256 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_IF;
#line 1604 "cajero.c"
  module->module_stmt = 0x00100100;
  if (((int)cob_cmp_numdisp (b_19, 1, 2LL, 0) == 0))
  {

    /* Line: 257       : PERFORM            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 257 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_PERFORM;
#line 1612 "cajero.c"
    module->module_stmt = 0x00100101;
    /* PERFORM MENU-OPERACIONES */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_30;
    goto l_7;
    l_30:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 14)
    goto *frame_ptr->return_address_ptr;

  /* Line: 260       : Paragraph MENU-ULT-MOVIMIENTOS    : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
  l_16:;
#line 260 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  PARAGRAPH_MENU__ULT__MOVIMIENTOS_l_16:	module->statement = STMT_ENTRY;
#line 1641 "cajero.c"
  module->module_stmt = 0x00100104;
  module->paragraph_name = st_9;

  /* Line: 261       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 261 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_DISPLAY;
#line 1648 "cajero.c"
  module->module_stmt = 0x00100105;
  cob_display (0, 1, 1, &c_41);

  /* Line: 262       : PERFORM            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 262 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_PERFORM;
#line 1655 "cajero.c"
  module->module_stmt = 0x00100106;
  *(b_33) = 49;
  for (;;)
  {
    /* Line: 263       : UNTIL              : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 263 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_UNTIL;
#line 1663 "cajero.c"
    module->module_stmt = 0x00100107;
    if (((int)cob_cmp_numdisp (b_33, 1, 5LL, 0) > 0))
      break;

    /* Line: 265       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 265 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_DISPLAY;
#line 1671 "cajero.c"
    module->module_stmt = 0x00100109;
    cob_display (0, 1, 3, 
    (cob_check_subscript (cob_get_numdisp (b_33, 1), 5, "WS-MOV-TIPO", 0),
    COB_SET_FLD (f0, 20, b_26 + 37LL * ((cob_s64_t)(cob_get_numdisp (b_33, 1)) - 1), &a_2) ), &c_42, 
    (cob_check_subscript (cob_get_numdisp (b_33, 1), 5, "WS-MOV-MONTO", 0),
    COB_SET_FLD (f1, 9, b_26 + 20 + 37LL * ((cob_s64_t)(cob_get_numdisp (b_33, 1)) - 1), &a_7) ));
    /* Line: 262       : VARYING            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 262 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_VARYING;
#line 1681 "cajero.c"
    module->module_stmt = 0x00100106;
    cob_add_int (&f_33, 1, 0);
  }

  /* Line: 270       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 270 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_MOVE;
#line 1689 "cajero.c"
  module->module_stmt = 0x0010010E;
  *(b_25) = 48;

  /* Line: 271       : PERFORM            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 271 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_PERFORM;
#line 1696 "cajero.c"
  module->module_stmt = 0x0010010F;
  for (;;)
  {
    /* Line: 271       : UNTIL              : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 271 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_UNTIL;
#line 1703 "cajero.c"
    module->module_stmt = 0x0010010F;
    if ((((int)cob_cmp_numdisp (b_25, 1, 1LL, 0) == 0) || 
        ((int)cob_cmp_numdisp (b_25, 1, 2LL, 0) == 0)))
      break;

    /* Line: 272       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 272 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_DISPLAY;
#line 1712 "cajero.c"
    module->module_stmt = 0x00100110;
    cob_display (0, 1, 1, &c_43);

    /* Line: 273       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 273 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_DISPLAY;
#line 1719 "cajero.c"
    module->module_stmt = 0x00100111;
    cob_display (0, 1, 1, &c_29);

    /* Line: 274       : ACCEPT             : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 274 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_ACCEPT;
#line 1726 "cajero.c"
    module->module_stmt = 0x00100112;
    cob_accept (&f_25);

    /* Line: 276       : EVALUATE           : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 276 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_EVALUATE;
#line 1733 "cajero.c"
    module->module_stmt = 0x00100114;

    /* Line: 277       : WHEN               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 277 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_WHEN;
#line 1739 "cajero.c"
    module->module_stmt = 0x00100115;

    if (((int)cob_cmp_numdisp (b_25, 1, 1LL, 0) == 0))
    {

      /* Line: 278       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 278 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_DISPLAY;
#line 1748 "cajero.c"
      module->module_stmt = 0x00100116;
      cob_display (0, 1, 1, &c_44);

      /* Line: 279       : ACCEPT             : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 279 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_ACCEPT;
#line 1755 "cajero.c"
      module->module_stmt = 0x00100117;
      cob_accept (NULL);

      /* Line: 280       : MOVE               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 280 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_MOVE;
#line 1762 "cajero.c"
      module->module_stmt = 0x00100118;
      *(b_25) = 50;
      goto l_17;
    }

    /* Line: 281       : WHEN               : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 281 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_WHEN;
#line 1771 "cajero.c"
    module->module_stmt = 0x00100119;

    if (((int)cob_cmp_numdisp (b_25, 1, 2LL, 0) == 0))
    {

      /* Line: 282       : CONTINUE           : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 282 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
      module->statement = STMT_CONTINUE;
#line 1780 "cajero.c"
      module->module_stmt = 0x0010011A;
      ;
      goto l_17;
    }

    /* WHEN OTHER */

    /* Line: 284       : DISPLAY            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 284 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_DISPLAY;
#line 1791 "cajero.c"
    module->module_stmt = 0x0010011C;
    cob_display (0, 1, 1, &c_16);

    /* Line: 285       : ACCEPT             : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 285 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_ACCEPT;
#line 1798 "cajero.c"
    module->module_stmt = 0x0010011D;
    cob_accept (NULL);

    /* End EVALUATE */
    l_17:;
  }

  /* Line: 289       : IF                 : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 289 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->statement = STMT_IF;
#line 1809 "cajero.c"
  module->module_stmt = 0x00100121;
  if (((int)cob_cmp_numdisp (b_25, 1, 2LL, 0) == 0))
  {

    /* Line: 290       : PERFORM            : C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 290 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
    module->statement = STMT_PERFORM;
#line 1817 "cajero.c"
    module->module_stmt = 0x00100122;
    /* PERFORM MENU-OPERACIONES */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_31;
    goto l_7;
    l_31:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 16)
    goto *frame_ptr->return_address_ptr;

  /* Line: 292       : last source line                  :C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
#line 292 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  module->module_stmt = 0x00100124;
#line 1845 "cajero.c"
  cob_nop ();


  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return 0;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  cajero_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE, Default byte: 0x00 */
  /* initialize field MENU-CHOICE */
#line 13 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  cob_nop ();
#line 1896 "cajero.c"
  *(cob_u8_ptr)(b_1) = 0x0;

  /* initialize field WS-CBF */
#line 21 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  cob_nop ();
#line 1902 "cajero.c"
  memset (b_8, 0x0, 6);

  /* initialize field WS-PIN-NUM */
#line 22 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  cob_nop ();
#line 1908 "cajero.c"
  memset (b_9, 0x0, 6);

  /* initialize field WS-VALIDO */
#line 23 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  cob_nop ();
#line 1914 "cajero.c"
  *(cob_u8_ptr)(b_10) = (unsigned char)'N';

  /* initialize field WS-MONTO-FORMAT */
#line 26 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  cob_nop ();
#line 1920 "cajero.c"
  memset (b_11, 0x0, 11);

  /* initialize field WS-MONTO */
#line 27 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  cob_nop ();
#line 1926 "cajero.c"
  memset (b_12, 0x0, 11);

  /* initialize field WS-OPCION-DEP */
#line 28 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  cob_nop ();
#line 1932 "cajero.c"
  *(b_13) = 48;

  /* initialize field WS-FIN */
#line 31 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  cob_nop ();
#line 1938 "cajero.c"
  *(cob_u8_ptr)(b_14) = 0x0;

  /* initialize field WS-SALDO */
#line 34 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  cob_nop ();
#line 1944 "cajero.c"
  memset (b_15, 48, 11);

  /* initialize field WS-SALDO-FORMAT */
#line 35 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  cob_nop ();
#line 1950 "cajero.c"
  memset (b_16, 0x0, 11);

  /* initialize field WS-MONTO-EXT */
#line 36 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  cob_nop ();
#line 1956 "cajero.c"
  memset (b_17, 0x0, 9);

  /* initialize field WS-MONTO-EXT-FOR */
#line 37 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  cob_nop ();
#line 1962 "cajero.c"
  memset (b_18, 0x0, 9);

  /* initialize field WS-OPCION-EXT */
#line 38 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  cob_nop ();
#line 1968 "cajero.c"
  *(cob_u8_ptr)(b_19) = 0x0;

  /* initialize field TOPE-EXT */
#line 39 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  cob_nop ();
#line 1974 "cajero.c"
  memcpy (b_20, "100000", 6);

  /* initialize field WS-OPCION-SALDO */
#line 42 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  cob_nop ();
#line 1980 "cajero.c"
  memset (b_21, 48, 9);

  /* initialize field WS-CBF-DESTINO */
#line 45 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  cob_nop ();
#line 1986 "cajero.c"
  memset (b_22, 0x0, 6);

  /* initialize field WS-MONTO-TRANSF */
#line 46 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  cob_nop ();
#line 1992 "cajero.c"
  memcpy (b_23, "000100000", 9);

  /* initialize field WS-MONTO-TRANSF-FOR */
#line 47 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  cob_nop ();
#line 1998 "cajero.c"
  memset (b_24, 0x0, 9);

  /* initialize field WS-OPCION-MOV */
#line 49 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  cob_nop ();
#line 2004 "cajero.c"
  *(cob_u8_ptr)(b_25) = 0x0;

  /* initialize field WS-MOVIMIENTOS */
#line 50 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  cob_nop ();
#line 2010 "cajero.c"
  memset (b_26, 0x0, 185);

  /* initialize field WS-INDICE-MOV */
#line 57 "C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"
  cob_nop ();
#line 2016 "cajero.c"
  *(b_33) = 48;


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'cajero' */

/* Initialize module structure for cajero */
static void cajero_module_init (cob_module *module)
{
  module->module_name = "cajero";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())cajero;
  module->module_cancel.funcptr = (void *(*)())cajero_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = ',';
  module->currency_symbol = '$';
  module->numeric_separator = '.';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 0;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

