/* Generated by           cobc 3.2.0 */
/* Generated from         C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
/* Generated at           Sep 10 2025 08:56:18 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\msys64\mingw64\bin\cobc.exe -x -std=cobol85 -g -I ./copybooks -debug C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Picture strings */

static const cob_pic_symbol p_1[] = {
	{'Z', 3},
	{'.', 1},
	{'Z', 3},
	{'.', 1},
	{'Z', 2},
	{'9', 1},
	{'\0', 1}
};
static const cob_pic_symbol p_2[] = {
	{'Z', 1},
	{'.', 1},
	{'Z', 3},
	{'.', 1},
	{'Z', 2},
	{'9', 1},
	{'\0', 1}
};


/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x10,   6,   0, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x10,   1,   0, 0x0000, NULL};
static const cob_field_attr a_5 =	{0x10,  11,   0, 0x0000, NULL};
static const cob_field_attr a_6 =	{0x24,   9,   0, 0x0000, p_1};
static const cob_field_attr a_7 =	{0x10,   9,   0, 0x0000, NULL};
static const cob_field_attr a_8 =	{0x24,   7,   0, 0x0000, p_2};


/* Constants */
static const cob_field c_1	= {30, (cob_u8_ptr)"==============================", &a_1};
static const cob_field c_2	= {30, (cob_u8_ptr)"=====Bienvenido al Cajero=====", &a_1};
static const cob_field c_3	= {27, (cob_u8_ptr)"    -Gracias por elegirnos-", &a_1};
static const cob_field c_4	= {31, (cob_u8_ptr)"# Ingrese su CBF de 6 digitos #", &a_1};
static const cob_field c_5	= {40, (cob_u8_ptr)"ERROR: Debe ingresar 6 digitos numericos", &a_1};
static const cob_field c_6	= {3, (cob_u8_ptr)"CLS", &a_1};
static const cob_field c_7	= {32, (cob_u8_ptr)"================================", &a_1};
static const cob_field c_8	= {33, (cob_u8_ptr)"// Por favor, elija una opcion \\\\", &a_1};
static const cob_field c_9	= {7, (cob_u8_ptr)"1.Saldo", &a_1};
static const cob_field c_10	= {15, (cob_u8_ptr)"2.Transferencia", &a_1};
static const cob_field c_11	= {10, (cob_u8_ptr)"3.Deposito", &a_1};
static const cob_field c_12	= {12, (cob_u8_ptr)"4.Extraccion", &a_1};
static const cob_field c_13	= {21, (cob_u8_ptr)"5.Ultimos Movimientos", &a_1};
static const cob_field c_14	= {7, (cob_u8_ptr)"6.Salir", &a_1};
static const cob_field c_15	= {11, (cob_u8_ptr)"Su opcion: ", &a_1};
static const cob_field c_16	= {15, (cob_u8_ptr)"Opcion invalida", &a_1};
static const cob_field c_17	= {23, (cob_u8_ptr)"Su saldo actual es de: ", &a_1};
static const cob_field c_18	= {1, (cob_u8_ptr)"$", &a_1};
static const cob_field c_19	= {19, (cob_u8_ptr)"1.Enviar por e-mail", &a_1};
static const cob_field c_20	= {34, (cob_u8_ptr)"2.Volver a pantalla de operaciones", &a_1};
static const cob_field c_21	= {22, (cob_u8_ptr)"Enviando por e-mail...", &a_1};
static const cob_field c_22	= {23, (cob_u8_ptr)"Ingrese el CBF destino:", &a_1};
static const cob_field c_23	= {27, (cob_u8_ptr)"Ingrese monto a transferir:", &a_1};
static const cob_field c_24	= {42, (cob_u8_ptr)"Fondos insuficientes. Operacion cancelada.", &a_1};
static const cob_field c_25	= {25, (cob_u8_ptr)"Trasferencia exitosa de $", &a_1};
static const cob_field c_26	= {23, (cob_u8_ptr)"Su nuevo saldo es de: $", &a_1};
static const cob_field c_27	= {26, (cob_u8_ptr)"Ingrese monto a depositar:", &a_1};
static const cob_field c_28	= {21, (cob_u8_ptr)"1. Confirmar Deposito", &a_1};
static const cob_field c_29	= {35, (cob_u8_ptr)"2. Volver a pantalla de operaciones", &a_1};
static const cob_field c_30	= {25, (cob_u8_ptr)"Deposito confirmado por $", &a_1};
static const cob_field c_31	= {24, (cob_u8_ptr)"Su saldo actual es de: $", &a_1};
static const cob_field c_32	= {24, (cob_u8_ptr)"Ingrese monto a extraer:", &a_1};
static const cob_field c_33	= {41, (cob_u8_ptr)"Fondos insuficientes. Ingrese otro monto.", &a_1};
static const cob_field c_34	= {27, (cob_u8_ptr)"Supera el tope permitido ($", &a_1};
static const cob_field c_35	= {2, (cob_u8_ptr)").", &a_1};
static const cob_field c_36	= {38, (cob_u8_ptr)"Ingrese un monto menor, apriete ENTER.", &a_1};
static const cob_field c_37	= {23, (cob_u8_ptr)"1. Confirmar Extraccion", &a_1};
static const cob_field c_38	= {23, (cob_u8_ptr)"Extraccion exitosa de $", &a_1};
static const cob_field c_39	= {17, (cob_u8_ptr)"Saldo restante: $", &a_1};
static const cob_field c_40	= {16, (cob_u8_ptr)"Opcion invalida.", &a_1};
static const cob_field c_41	= {33, (cob_u8_ptr)"====== Ultimos Movimientos ======", &a_1};
static const cob_field c_42	= {6, (cob_u8_ptr)" por $", &a_1};
static const cob_field c_43	= {20, (cob_u8_ptr)"1. Enviar por e-mail", &a_1};
static const cob_field c_44	= {38, (cob_u8_ptr)"Enviando ultimos movimientos por email", &a_1};


/* Strings */
static const char st_1[]	= "MAIN-PROGRAM";
static const char st_2[]	= "DISPLAY-MENU";
static const char st_3[]	= "VALIDAR-PIN";
static const char st_4[]	= "MENU-OPERACIONES";
static const char st_5[]	= "MENU-SALDO";
static const char st_6[]	= "MENU-TRANSFERENCIA";
static const char st_7[]	= "MENU-DEPOSITO";
static const char st_8[]	= "MENU-EXTRACCION";
static const char st_9[]	= "MENU-ULT-MOVIMIENTOS";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"C:\\msys64\\home\\Usuario\\cobol\\cbf\\cobol-final-project\\cajero\\cajero.cbl"};

static void COB_INLINE COB_A_INLINE
cob_check_subscript_inline (const int i, const int max,
			const char* name, const int odo_item)
{
	if (i < 1 || i > max) {
		cob_check_subscript (i, max, name, odo_item);
	}
}
#define cob_check_subscript	cob_check_subscript_inline


#define cob_nop	if (!module) cob_nop


static int COB_INLINE COB_A_INLINE
cob_get_numdisp (const void *data, const int size)
{
	register const unsigned char	*p = (const unsigned char *)data;
	register int	n;
	register int	val = 0;
	for (n = 0; n < val; ++n, ++p) {
		if (*p > '0' && *p <= '9')
			break;
	}
	for (n = 0; n < size; ++n, ++p) {
		val = (val * 10)
		    + (*p & 0x0F);
	}
	return val;
}

