/* Generated by           cobc 3.2.0 */
/* Generated from         C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */
/* Generated at           Sep 10 2025 08:56:18 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\msys64\mingw64\bin\cobc.exe -x -std=cobol85 -g -I ./copybooks -debug C:\msys64\home\Usuario\cobol\cbf\cobol-final-project\cajero\cajero.cbl */

/* Program local variables for 'cajero' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d_0 = NULL;
cob_decimal	*d_1 = NULL;


/* Local cob_field items */
cob_field		f0;
cob_field		f1;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame_ext	*frame_overflow;
struct cob_frame_ext	*frame_ptr;
struct cob_frame_ext	frame_stack[255];


/* Data storage */
static cob_u8_t	b_1[1] __attribute__((aligned));	/* MENU-CHOICE */
static cob_u8_t	b_8[6] __attribute__((aligned));	/* WS-CBF */
static cob_u8_t	b_9[6] __attribute__((aligned));	/* WS-PIN-NUM */
static cob_u8_t	b_10[1] __attribute__((aligned));	/* WS-VALIDO */
static cob_u8_t	b_11[11] __attribute__((aligned));	/* WS-MONTO-FORMAT */
static cob_u8_t	b_12[11] __attribute__((aligned));	/* WS-MONTO */
static cob_u8_t	b_13[1] __attribute__((aligned));	/* WS-OPCION-DEP */
static cob_u8_t	b_14[1] __attribute__((aligned));	/* WS-FIN */
static cob_u8_t	b_15[11] __attribute__((aligned));	/* WS-SALDO */
static cob_u8_t	b_16[11] __attribute__((aligned));	/* WS-SALDO-FORMAT */
static cob_u8_t	b_17[9] __attribute__((aligned));	/* WS-MONTO-EXT */
static cob_u8_t	b_18[9] __attribute__((aligned));	/* WS-MONTO-EXT-FOR */
static cob_u8_t	b_19[1] __attribute__((aligned));	/* WS-OPCION-EXT */
static cob_u8_t	b_20[6] __attribute__((aligned));	/* TOPE-EXT */
static cob_u8_t	b_21[9] __attribute__((aligned));	/* WS-OPCION-SALDO */
static cob_u8_t	b_22[6] __attribute__((aligned));	/* WS-CBF-DESTINO */
static cob_u8_t	b_23[9] __attribute__((aligned));	/* WS-MONTO-TRANSF */
static cob_u8_t	b_24[9] __attribute__((aligned));	/* WS-MONTO-TRANSF-FOR */
static cob_u8_t	b_25[1] __attribute__((aligned));	/* WS-OPCION-MOV */
static cob_u8_t	b_26[185] __attribute__((aligned));	/* WS-MOVIMIENTOS */
static cob_u8_t	b_33[1] __attribute__((aligned));	/* WS-INDICE-MOV */

/* End of local data storage */


/* Fields (local) */
static cob_field f_1	= {1, b_1, &a_4};	/* MENU-CHOICE */
static cob_field f_8	= {6, b_8, &a_2};	/* WS-CBF */
static cob_field f_9	= {6, b_9, &a_3};	/* WS-PIN-NUM */
static cob_field f_11	= {11, b_11, &a_6};	/* WS-MONTO-FORMAT */
static cob_field f_12	= {11, b_12, &a_5};	/* WS-MONTO */
static cob_field f_13	= {1, b_13, &a_4};	/* WS-OPCION-DEP */
static cob_field f_15	= {11, b_15, &a_5};	/* WS-SALDO */
static cob_field f_16	= {11, b_16, &a_6};	/* WS-SALDO-FORMAT */
static cob_field f_17	= {9, b_17, &a_7};	/* WS-MONTO-EXT */
static cob_field f_18	= {9, b_18, &a_8};	/* WS-MONTO-EXT-FOR */
static cob_field f_19	= {1, b_19, &a_4};	/* WS-OPCION-EXT */
static cob_field f_20	= {6, b_20, &a_3};	/* TOPE-EXT */
static cob_field f_21	= {9, b_21, &a_7};	/* WS-OPCION-SALDO */
static cob_field f_22	= {6, b_22, &a_3};	/* WS-CBF-DESTINO */
static cob_field f_23	= {9, b_23, &a_7};	/* WS-MONTO-TRANSF */
static cob_field f_24	= {9, b_24, &a_8};	/* WS-MONTO-TRANSF-FOR */
static cob_field f_25	= {1, b_25, &a_4};	/* WS-OPCION-MOV */
static cob_field f_33	= {1, b_33, &a_4};	/* WS-INDICE-MOV */

/* End of fields */

