/* Generated by           cobc 3.2.0 */
/* Generated from         C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
/* Generated at           Sep 08 2025 04:44:17 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\msys64\mingw64\bin\cobc.exe -x -std=cobol85 -g -I ./copybooks -debug C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */

/* Program local variables for 'ALTAS' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call pointers */
static char	call_fence_pre[8];
static cob_call_union	call_CREAR__CBF;
static char	call_fence_post[8];

/* Call parameters */
cob_field		*cob_procedure_params[2];

/* Perform frame stack */
struct cob_frame_ext	*frame_overflow;
struct cob_frame_ext	*frame_ptr;
struct cob_frame_ext	frame_stack[255];


/* Data storage */
static cob_u8_t	b_1[2] __attribute__((aligned));	/* MENU-CHOICE-STR */
static cob_u8_t	b_2[1] __attribute__((aligned));	/* MENU-CHOICE */
static cob_u8_t	b_5_fence_pre[8] __attribute__((aligned));
static cob_u8_t	b_5[5] __attribute__((aligned));	/* ID-CUENTA */
static cob_u8_t	b_5_fence_post[8] __attribute__((aligned));
static cob_u8_t	b_11_fence_pre[8] __attribute__((aligned));
static cob_u8_t	b_11[6] __attribute__((aligned));	/* CLAVE-BANCARIA */
static cob_u8_t	b_11_fence_post[8] __attribute__((aligned));

/* End of local data storage */


/* Fields (local) */
static cob_field f_1	= {2, b_1, &a_2};	/* MENU-CHOICE-STR */
static cob_field f_2	= {1, b_2, &a_3};	/* MENU-CHOICE */
static cob_field f_5	= {5, b_5, &a_4};	/* ID-CUENTA */
static cob_field f_11	= {6, b_11, &a_2};	/* CLAVE-BANCARIA */

/* End of fields */

