/* Generated by           cobc 3.2.0 */
/* Generated from         C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
/* Generated at           Sep 09 2025 21:18:00 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\msys64\mingw64\bin\cobc.exe -x -std=default -g -I ./includes -debug C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl buscar-cliente.cbl calculate-cbf.cbl crear-cbf.cbl guardar-cliente.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 09 2025 21:18:00"
#define  COB_MODULE_DATE		20250909
#define  COB_MODULE_TIME		211800

/* Global variables */
#include "altas.c.h"

/* Function prototypes */

static int		ALTAS__CLIENTES ();
static int		ALTAS__CLIENTES_ (const int);
static void		ALTAS__CLIENTES_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (ALTAS__CLIENTES ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'ALTAS-CLIENTES' */

/* ENTRY 'ALTAS__CLIENTES' */

static int
ALTAS__CLIENTES ()
{
  return ALTAS__CLIENTES_ (0);
}

static int
ALTAS__CLIENTES_ (const int entry)
{
  /* Program local variables */
  #include "altas.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;
  module->frame_ptr = frame_stack;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  module->frame_ptr->section_name = "";
  module->frame_ptr->paragraph_name = "ALTAS-CLIENTES";
  module->frame_ptr->module_stmt = 0x00100017;
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 23        : Entry     ALTAS-CLIENTES          : C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
  l_2:;
#line 23 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
  ENTRY_ALTAS__CLIENTES:	module->statement = STMT_ENTRY;
#line 109 "altas.c"
  module->module_stmt = 0x00100017;
  module->section_name = NULL;
  module->paragraph_name = NULL;

  /* Line: 23        : Paragraph MAIN-PROCEDURE          : C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
#line 23 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
  PARAGRAPH_MAIN__PROCEDURE_l_4:	module->statement = STMT_ENTRY;
#line 117 "altas.c"
  module->paragraph_name = st_1;

  /* Line: 24        : PERFORM            : C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
#line 24 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
  module->statement = STMT_PERFORM;
#line 123 "altas.c"
  module->module_stmt = 0x00100018;
  for (;;)
  {
    /* Line: 24        : UNTIL              : C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
#line 24 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
    module->statement = STMT_UNTIL;
#line 130 "altas.c"
    module->module_stmt = 0x00100018;
    if (((int)cob_cmp_numdisp (b_18, 1, 2LL, 0) == 0))
      break;
    /* PERFORM DISPLAY-MENU */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 5;
    frame_ptr->return_address_ptr = &&l_7;
    goto l_5;
    l_7:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;
  }

  /* Line: 25        : STOP RUN           : C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
#line 25 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
  module->statement = STMT_STOP_RUN;
#line 156 "altas.c"
  module->module_stmt = 0x00100019;
  cob_stop_run (b_2);

  /* Line: 27        : Paragraph DISPLAY-MENU            : C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
  l_5:;
#line 27 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
  PARAGRAPH_DISPLAY__MENU_l_5:	module->statement = STMT_ENTRY;
#line 164 "altas.c"
  module->module_stmt = 0x0010001B;
  module->paragraph_name = st_2;

  /* Line: 28        : DISPLAY            : C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
#line 28 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
  module->statement = STMT_DISPLAY;
#line 171 "altas.c"
  module->module_stmt = 0x0010001C;
  cob_display (0, 1, 1, &c_1);

  /* Line: 29        : DISPLAY            : C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
#line 29 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
  module->statement = STMT_DISPLAY;
#line 178 "altas.c"
  module->module_stmt = 0x0010001D;
  cob_display (0, 1, 1, &c_2);

  /* Line: 30        : DISPLAY            : C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
#line 30 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
  module->statement = STMT_DISPLAY;
#line 185 "altas.c"
  module->module_stmt = 0x0010001E;
  cob_display (0, 1, 1, &c_1);

  /* Line: 31        : DISPLAY            : C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
#line 31 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
  module->statement = STMT_DISPLAY;
#line 192 "altas.c"
  module->module_stmt = 0x0010001F;
  cob_display (0, 1, 1, &c_3);

  /* Line: 32        : DISPLAY            : C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
#line 32 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
  module->statement = STMT_DISPLAY;
#line 199 "altas.c"
  module->module_stmt = 0x00100020;
  cob_display (0, 1, 1, &c_4);

  /* Line: 33        : DISPLAY            : C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
#line 33 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
  module->statement = STMT_DISPLAY;
#line 206 "altas.c"
  module->module_stmt = 0x00100021;
  cob_display (0, 0, 1, &c_5);

  /* Line: 34        : ACCEPT             : C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
#line 34 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
  module->statement = STMT_ACCEPT;
#line 213 "altas.c"
  module->module_stmt = 0x00100022;
  cob_accept (&f_17);

  /* Line: 35        : MOVE               : C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
#line 35 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
  module->statement = STMT_MOVE;
#line 220 "altas.c"
  module->module_stmt = 0x00100023;
  cob_move (cob_intr_numval (&f_17), &f_18);

  /* Line: 37        : EVALUATE           : C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
#line 37 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
  module->statement = STMT_EVALUATE;
#line 227 "altas.c"
  module->module_stmt = 0x00100025;

  /* Line: 38        : WHEN               : C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
#line 38 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
  module->statement = STMT_WHEN;
#line 233 "altas.c"
  module->module_stmt = 0x00100026;

  if (((int)cob_cmp_numdisp (b_18, 1, 1LL, 0) == 0))
  {

    /* Line: 39        : CALL               : C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
#line 39 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
    module->statement = STMT_CALL;
#line 242 "altas.c"
    module->module_stmt = 0x00100027;
    cob_procedure_params[0] = &f_21;
    cob_procedure_params[1] = &f_27;
    cob_glob_ptr->cob_call_params = 2;
    cob_glob_ptr->cob_stmt_exception = 0;
    if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
    if (memcmp (b_21_fence_pre, "\x00\x00\x00\x00\x00\x00\x00", 8) == 0) {
      memcpy (b_21_fence_pre, "\xFF\xFE\xFD\xFC\xFB\xFA\xFF", 8);
      memcpy (b_21_fence_post, "\xFA\xFB\xFC\xFD\xFE\xFF\xFA", 8);
    } else {
      cob_check_fence (b_21_fence_pre, b_21_fence_post, STMT_BEFORE_CALL, "ID-CUENTA");
    }
    if (memcmp (b_27_fence_pre, "\x00\x00\x00\x00\x00\x00\x00", 8) == 0) {
      memcpy (b_27_fence_pre, "\xFF\xFE\xFD\xFC\xFB\xFA\xFF", 8);
      memcpy (b_27_fence_post, "\xFA\xFB\xFC\xFD\xFE\xFF\xFA", 8);
    } else {
      cob_check_fence (b_27_fence_pre, b_27_fence_post, STMT_BEFORE_CALL, "CLAVE-BANCARIA");
    }
        if (unlikely(call_CREAR__CBF.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
    {
      call_CREAR__CBF.funcvoid = cob_resolve_cobol ("CREAR-CBF", 0, 1);
    }
    b_2 = ((int (*)(void *, void *))call_CREAR__CBF.funcint) (b_21, b_27);
    cob_check_fence (b_21_fence_pre, b_21_fence_post, STMT_CALL, "ID-CUENTA");
    cob_check_fence (b_27_fence_pre, b_27_fence_post, STMT_CALL, "CLAVE-BANCARIA");
    cob_check_fence (call_fence_pre, call_fence_post, STMT_CALL, NULL);
    goto l_6;
  }

  /* Line: 40        : WHEN               : C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
#line 40 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
  module->statement = STMT_WHEN;
#line 275 "altas.c"
  module->module_stmt = 0x00100028;

  if (((int)cob_cmp_numdisp (b_18, 1, 2LL, 0) == 0))
  {

    /* Line: 41        : CONTINUE           : C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
#line 41 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
    module->statement = STMT_CONTINUE;
#line 284 "altas.c"
    module->module_stmt = 0x00100029;
    ;
    goto l_6;
  }

  /* WHEN OTHER */

  /* Line: 43        : DISPLAY            : C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
#line 43 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
  module->statement = STMT_DISPLAY;
#line 295 "altas.c"
  module->module_stmt = 0x0010002B;
  cob_display (0, 1, 1, &c_6);

  /* End EVALUATE */
  l_6:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address_ptr;

  /* Line: 46        : last source line                  :C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
#line 46 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
  module->module_stmt = 0x0010002E;
#line 309 "altas.c"
  cob_nop ();


  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  ALTAS__CLIENTES_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize call-pointer memory fence */
  memcpy (call_fence_pre, "\xFF\xFE\xFD\xFC\xFB\xFA\xFF", 8);
  memcpy (call_fence_post, "\xFA\xFB\xFC\xFD\xFE\xFF\xFA", 8);

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field MENU-CHOICE-STR */
#line 9 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
  cob_nop ();
#line 367 "altas.c"
  memset (b_17, (unsigned char)' ', 2);

  /* initialize field MENU-CHOICE */
#line 10 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
  cob_nop ();
#line 373 "altas.c"
  *(cob_u8_ptr)(b_18) = (unsigned char)'0';

  /* initialize field ID-CUENTA */
#line 14 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
  cob_nop ();
#line 379 "altas.c"
  memset (b_21, (unsigned char)'0', 5);

  /* initialize field CLAVE-BANCARIA */
#line 20 "C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"
  cob_nop ();
#line 385 "altas.c"
  memset (b_27, (unsigned char)' ', 6);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'ALTAS-CLIENTES' */

/* Initialize module structure for ALTAS-CLIENTES */
static void ALTAS__CLIENTES_module_init (cob_module *module)
{
  module->module_name = "ALTAS-CLIENTES";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())ALTAS__CLIENTES;
  module->module_cancel.funcptr = (void *(*)())ALTAS__CLIENTES_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

