/* Generated by           cobc 3.2.0 */
/* Generated from         C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
/* Generated at           Sep 09 2025 20:38:36 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\msys64\mingw64\bin\cobc.exe -x -std=default -g -I ./copybooks -debug C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl buscar-cliente.cbl calculate-cbf.cbl crear-cbf.cbl guardar-cliente.cbl */

/* Program local variables for 'ALTAS-CLIENTES' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Call pointers */
static char	call_fence_pre[8];
static cob_call_union	call_CREAR__CBF;
static char	call_fence_post[8];

/* Call parameters */
cob_field		*cob_procedure_params[2];

/* Perform frame stack */
struct cob_frame_ext	*frame_overflow;
struct cob_frame_ext	*frame_ptr;
struct cob_frame_ext	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_17[2] __attribute__((aligned));	/* MENU-CHOICE-STR */
static cob_u8_t	b_18[1] __attribute__((aligned));	/* MENU-CHOICE */
static cob_u8_t	b_21_fence_pre[8] __attribute__((aligned));
static cob_u8_t	b_21[5] __attribute__((aligned));	/* ID-CUENTA */
static cob_u8_t	b_21_fence_post[8] __attribute__((aligned));
static cob_u8_t	b_27_fence_pre[8] __attribute__((aligned));
static cob_u8_t	b_27[6] __attribute__((aligned));	/* CLAVE-BANCARIA */
static cob_u8_t	b_27_fence_post[8] __attribute__((aligned));

/* End of local data storage */


/* Fields (local) */
static cob_field f_17	= {2, b_17, &a_2};	/* MENU-CHOICE-STR */
static cob_field f_18	= {1, b_18, &a_3};	/* MENU-CHOICE */
static cob_field f_21	= {5, b_21, &a_4};	/* ID-CUENTA */
static cob_field f_27	= {6, b_27, &a_2};	/* CLAVE-BANCARIA */

/* End of fields */

