/* Generated by           cobc 3.2.0 */
/* Generated from         C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl */
/* Generated at           Sep 09 2025 21:18:00 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\msys64\mingw64\bin\cobc.exe -x -std=default -g -I ./includes -debug C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl buscar-cliente.cbl calculate-cbf.cbl crear-cbf.cbl guardar-cliente.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x10,   1,   0, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x01,   0,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {49, (cob_u8_ptr)"-------------------------------------------------", &a_1};
static const cob_field c_2	= {49, (cob_u8_ptr)"---PROGRAMA CALCULO DE CLAVE BANCARIA FICTICIA---", &a_1};
static const cob_field c_3	= {35, (cob_u8_ptr)"1. Crear claves bancarias desde CSV", &a_1};
static const cob_field c_4	= {8, (cob_u8_ptr)"2. Salir", &a_1};
static const cob_field c_5	= {11, (cob_u8_ptr)"SU OPCION: ", &a_1};
static const cob_field c_6	= {15, (cob_u8_ptr)"OPCION INVALIDA", &a_1};


/* Strings */
static const char st_1[]	= "MAIN-PROCEDURE";
static const char st_2[]	= "DISPLAY-MENU";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"C:\\msys64\\home\\lopez\\COBOL\\cajero\\altas\\altas.cbl"};

static void COB_INLINE COB_A_INLINE
cob_check_fence_inline (const char *fence_pre, const char *fence_post,
	const enum cob_statement stmt, const char *name)
{
	if (memcmp (fence_pre, "\xFF\xFE\xFD\xFC\xFB\xFA\xFF", 8)
	 || memcmp (fence_post, "\xFA\xFB\xFC\xFD\xFE\xFF\xFA", 8)) {
		cob_check_fence (fence_pre, fence_post, stmt, name);
	}
}
#define cob_check_fence	cob_check_fence_inline


#define cob_nop	if (!module) cob_nop

