/* Generated by           cobc 3.2.0 */
/* Generated from         buscar-cliente.cbl */
/* Generated at           Sep 09 2025 20:38:37 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\msys64\mingw64\bin\cobc.exe -x -std=default -g -I ./copybooks -debug C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl buscar-cliente.cbl calculate-cbf.cbl crear-cbf.cbl guardar-cliente.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"buscar-cliente.cbl"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 09 2025 20:38:37"
#define  COB_MODULE_DATE		20250909
#define  COB_MODULE_TIME		203837

/* Global variables */
#include "buscar-cliente.c.h"

/* Function prototypes */

COB_EXT_EXPORT int		BUSCAR__CLIENTE (cob_u8_t *, cob_u8_t *);
static int		BUSCAR__CLIENTE_ (const int, cob_u8_t *, cob_u8_t *);
static void		BUSCAR__CLIENTE_module_init (cob_module *module);

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'BUSCAR-CLIENTE' */

/* ENTRY 'BUSCAR__CLIENTE' */

int
BUSCAR__CLIENTE (cob_u8_t *b_17, cob_u8_t *b_18)
{
  cob_u8_t *cob_parm_17 = NULL;	/* linkage for CLAVE-BANCARIA */
  cob_u8_t *cob_parm_18 = NULL;	/* linkage for ID-CUENTA-STR */

  /* Get current number of call parameters,
     if the parameter count is unknown, set it to all */
  if (cob_get_global_ptr ()->cob_current_module) {
  	cob_call_params = cob_get_global_ptr ()->cob_call_params;
  } else {
  	cob_call_params = 2;
  }

  /* Set the parameter list */
  if (cob_call_params > 0) {
    cob_parm_17 = b_17;
  }
  if (cob_call_params > 1) {
    cob_parm_18 = b_18;
  }

#line 12 "buscar-cliente.cbl"
  if (cob_check_linkage_size ("BUSCAR__CLIENTE", "CLAVE-BANCARIA", 1, 0, 6, st_source_files, 1048588)) {
#line 65 "buscar-cliente.c"
  	return -1;
  }
#line 12 "buscar-cliente.cbl"
  if (cob_check_linkage_size ("BUSCAR__CLIENTE", "ID-CUENTA-STR", 2, 0, 6, st_source_files, 1048588)) {
#line 70 "buscar-cliente.c"
  	return -1;
  }
  return BUSCAR__CLIENTE_ (0, cob_parm_17, cob_parm_18);
}

static int
BUSCAR__CLIENTE_ (const int entry, cob_u8_t *b_17, cob_u8_t *b_18)
{
  /* Program local variables */
  #include "buscar-cliente.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;
  module->frame_ptr = frame_stack;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Store last parameters for possible later lookup */
  last_b_17 = b_17;
  last_b_18 = b_18;

  /* Entry dispatch */
  module->frame_ptr->section_name = "";
  module->frame_ptr->paragraph_name = "BUSCAR-CLIENTE";
  module->frame_ptr->module_stmt = 0x0010000D;
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 13        : Entry     BUSCAR-CLIENTE          : buscar-cliente.cbl */
  l_2:;
#line 13 "buscar-cliente.cbl"
  ENTRY_BUSCAR__CLIENTE:	module->statement = STMT_ENTRY;
#line 134 "buscar-cliente.c"
  module->module_stmt = 0x0010000D;
  module->section_name = NULL;
  module->paragraph_name = NULL;

  /* Line: 13        : DISPLAY            : buscar-cliente.cbl */
#line 13 "buscar-cliente.cbl"
  module->statement = STMT_DISPLAY;
#line 142 "buscar-cliente.c"
  cob_display (0, 1, 1, &c_1);

  /* Line: 14        : MOVE               : buscar-cliente.cbl */
#line 14 "buscar-cliente.cbl"
  module->statement = STMT_MOVE;
#line 148 "buscar-cliente.c"
  module->module_stmt = 0x0010000E;
  memset (b_18, 48, 6);

  /* Line: 16        : GOBACK             : buscar-cliente.cbl */
#line 16 "buscar-cliente.cbl"
  module->statement = STMT_GOBACK;
#line 155 "buscar-cliente.c"
  module->module_stmt = 0x00100010;
  goto exit_program;

  /* Line: 17        : last source line                  :buscar-cliente.cbl */
#line 17 "buscar-cliente.cbl"
  module->module_stmt = 0x00100011;
#line 162 "buscar-cliente.c"
  cob_nop ();


  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  BUSCAR__CLIENTE_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'BUSCAR-CLIENTE' */

/* Initialize module structure for BUSCAR-CLIENTE */
static void BUSCAR__CLIENTE_module_init (cob_module *module)
{
  module->module_name = "BUSCAR-CLIENTE";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())BUSCAR__CLIENTE;
  module->module_cancel.funcptr = (void *(*)())BUSCAR__CLIENTE_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 2;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

