/* Generated by           cobc 3.2.0 */
/* Generated from         buscar-cliente.cbl */
/* Generated at           Sep 09 2025 21:18:00 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\msys64\mingw64\bin\cobc.exe -x -std=default -g -I ./includes -debug C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl buscar-cliente.cbl calculate-cbf.cbl crear-cbf.cbl guardar-cliente.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};


/* Constants */
static const cob_field c_1	= {45, (cob_u8_ptr)"ESTA FUNCION LA DESARROLLA EL EQUIPO DE PABLO", &a_1};


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"buscar-cliente.cbl"};

#define cob_nop	if (!module) cob_nop

