/* Generated by           cobc 3.2.0 */
/* Generated from         buscar-cliente.cbl */
/* Generated at           Sep 08 2025 04:12:51 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\msys64\mingw64\bin\cobc.exe -x -I C:\msys64\home\lopez\COBOL\cajero-automatico\includes -g -o main.exe C:\msys64\home\lopez\COBOL\cajero-automatico\main.cbl calculate-cbf.cbl crear-cbf.cbl buscar-cliente.cbl guardar-cliente.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};


/* Constants */
static const cob_field c_1	= {45, (cob_u8_ptr)"ESTA FUNCION LA DESARROLLA EL EQUIPO DE PABLO", &a_1};


#define cob_nop	if (!module) cob_nop

