/* Generated by           cobc 3.2.0 */
/* Generated from         calculate-cbf.cbl */
/* Generated at           Sep 09 2025 21:18:01 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\msys64\mingw64\bin\cobc.exe -x -std=default -g -I ./includes -debug C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl buscar-cliente.cbl calculate-cbf.cbl crear-cbf.cbl guardar-cliente.cbl */

/* Program local variables for 'CALCULATE-CBF' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d_0 = NULL;
cob_decimal	*d_1 = NULL;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */

/* Last USING parameters for possible later lookup */
static unsigned char	*last_b_21;
static unsigned char	*last_b_27;

/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame_ext	*frame_overflow;
struct cob_frame_ext	*frame_ptr;
struct cob_frame_ext	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_17[4] __attribute__((aligned));	/* SUMA-DIGITOS */
static cob_u8_t	b_18[4] __attribute__((aligned));	/* TMP */
static cob_u8_t	b_19[2] __attribute__((aligned));	/* RESTO */
static cob_u8_t	b_20[1] __attribute__((aligned));	/* DV */

/* End of local data storage */


/* Fields (local) */
static cob_field f_17	= {4, b_17, &a_2};	/* SUMA-DIGITOS */
static cob_field f_18	= {4, b_18, &a_2};	/* TMP */
static cob_field f_19	= {2, b_19, &a_4};	/* RESTO */
static cob_field f_20	= {1, b_20, &a_1};	/* DV */
static cob_field f_22	= {1, NULL, &a_1};	/* ID-D1 */
static cob_field f_23	= {1, NULL, &a_1};	/* ID-D2 */
static cob_field f_24	= {1, NULL, &a_1};	/* ID-D3 */
static cob_field f_25	= {1, NULL, &a_1};	/* ID-D4 */
static cob_field f_26	= {1, NULL, &a_1};	/* ID-D5 */

/* End of fields */

