/* Generated by           cobc 3.2.0 */
/* Generated from         calculate-cbf.cbl */
/* Generated at           Sep 09 2025 20:38:37 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\msys64\mingw64\bin\cobc.exe -x -std=default -g -I ./copybooks -debug C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl buscar-cliente.cbl calculate-cbf.cbl crear-cbf.cbl guardar-cliente.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"calculate-cbf.cbl"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 09 2025 20:38:37"
#define  COB_MODULE_DATE		20250909
#define  COB_MODULE_TIME		203837

/* Global variables */
#include "calculate-cbf.c.h"

/* Function prototypes */

COB_EXT_EXPORT int		CALCULATE__CBF (cob_u8_t *, cob_u8_t *);
static int		CALCULATE__CBF_ (const int, cob_u8_t *, cob_u8_t *);
static void		CALCULATE__CBF_module_init (cob_module *module);

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'CALCULATE-CBF' */

/* ENTRY 'CALCULATE__CBF' */

int
CALCULATE__CBF (cob_u8_t *b_21, cob_u8_t *b_27)
{
  cob_u8_t *cob_parm_21 = NULL;	/* linkage for ID-CUENTA */
  cob_u8_t *cob_parm_27 = NULL;	/* linkage for CLAVE-BANCARIA */

  /* Get current number of call parameters,
     if the parameter count is unknown, set it to all */
  if (cob_get_global_ptr ()->cob_current_module) {
  	cob_call_params = cob_get_global_ptr ()->cob_call_params;
  } else {
  	cob_call_params = 2;
  }

  /* Set the parameter list */
  if (cob_call_params > 0) {
    cob_parm_21 = b_21;
  }
  if (cob_call_params > 1) {
    cob_parm_27 = b_27;
  }

#line 21 "calculate-cbf.cbl"
  if (cob_check_linkage_size ("CALCULATE__CBF", "ID-CUENTA", 1, 0, 5, st_source_files, 1048597)) {
#line 66 "calculate-cbf.c"
  	return -1;
  }
#line 21 "calculate-cbf.cbl"
  if (cob_check_linkage_size ("CALCULATE__CBF", "CLAVE-BANCARIA", 2, 0, 7, st_source_files, 1048597)) {
#line 71 "calculate-cbf.c"
  	return -1;
  }
  return CALCULATE__CBF_ (0, cob_parm_21, cob_parm_27);
}

static int
CALCULATE__CBF_ (const int entry, cob_u8_t *b_21, cob_u8_t *b_27)
{
  /* Program local variables */
  #include "calculate-cbf.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;
  module->frame_ptr = frame_stack;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d_0, &d_1);

  /* Increment module active */
  module->module_active++;

  /* Store last parameters for possible later lookup */
  last_b_21 = b_21;
  last_b_27 = b_27;

  /* Entry dispatch */
  module->frame_ptr->section_name = "";
  module->frame_ptr->paragraph_name = "CALCULATE-CBF";
  module->frame_ptr->module_stmt = 0x00100016;
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 22        : Entry     CALCULATE-CBF           : calculate-cbf.cbl */
  l_2:;
#line 22 "calculate-cbf.cbl"
  ENTRY_CALCULATE__CBF:	module->statement = STMT_ENTRY;
#line 138 "calculate-cbf.c"
  module->module_stmt = 0x00100016;
  module->section_name = NULL;
  module->paragraph_name = NULL;

  /* Line: 22        : MOVE               : calculate-cbf.cbl */
#line 22 "calculate-cbf.cbl"
  module->statement = STMT_MOVE;
#line 146 "calculate-cbf.c"
  memset (b_17, 48, 4);

  /* Line: 24        : MULTIPLY           : calculate-cbf.cbl */
#line 24 "calculate-cbf.cbl"
  module->statement = STMT_MULTIPLY;
#line 152 "calculate-cbf.c"
  module->module_stmt = 0x00100018;
  cob_decimal_set_llint (d_0, 6LL);
  cob_check_numeric (COB_SET_DATA (f_22, b_21), "ID-D1");
  cob_decimal_set_field (d_1, COB_SET_DATA (f_22, b_21));
  cob_decimal_mul (d_0, d_1);
  cob_decimal_get_field (d_0, &f_18, 0);

  /* Line: 25        : ADD                : calculate-cbf.cbl */
#line 25 "calculate-cbf.cbl"
  module->statement = STMT_ADD;
#line 163 "calculate-cbf.c"
  module->module_stmt = 0x00100019;
  cob_check_numeric (&f_18, "TMP");
  cob_check_numeric (&f_17, "SUMA-DIGITOS");
  cob_add_int (&f_17, cob_get_numdisp (b_18, 4), 0);

  /* Line: 27        : MULTIPLY           : calculate-cbf.cbl */
#line 27 "calculate-cbf.cbl"
  module->statement = STMT_MULTIPLY;
#line 172 "calculate-cbf.c"
  module->module_stmt = 0x0010001B;
  cob_decimal_set_llint (d_0, 5LL);
  cob_check_numeric (COB_SET_DATA (f_23, b_21 + 1), "ID-D2");
  cob_decimal_set_field (d_1, COB_SET_DATA (f_23, b_21 + 1));
  cob_decimal_mul (d_0, d_1);
  cob_decimal_get_field (d_0, &f_18, 0);

  /* Line: 28        : ADD                : calculate-cbf.cbl */
#line 28 "calculate-cbf.cbl"
  module->statement = STMT_ADD;
#line 183 "calculate-cbf.c"
  module->module_stmt = 0x0010001C;
  cob_check_numeric (&f_18, "TMP");
  cob_check_numeric (&f_17, "SUMA-DIGITOS");
  cob_add_int (&f_17, cob_get_numdisp (b_18, 4), 0);

  /* Line: 30        : MULTIPLY           : calculate-cbf.cbl */
#line 30 "calculate-cbf.cbl"
  module->statement = STMT_MULTIPLY;
#line 192 "calculate-cbf.c"
  module->module_stmt = 0x0010001E;
  cob_decimal_set_llint (d_0, 4LL);
  cob_check_numeric (COB_SET_DATA (f_24, b_21 + 2), "ID-D3");
  cob_decimal_set_field (d_1, COB_SET_DATA (f_24, b_21 + 2));
  cob_decimal_mul (d_0, d_1);
  cob_decimal_get_field (d_0, &f_18, 0);

  /* Line: 31        : ADD                : calculate-cbf.cbl */
#line 31 "calculate-cbf.cbl"
  module->statement = STMT_ADD;
#line 203 "calculate-cbf.c"
  module->module_stmt = 0x0010001F;
  cob_check_numeric (&f_18, "TMP");
  cob_check_numeric (&f_17, "SUMA-DIGITOS");
  cob_add_int (&f_17, cob_get_numdisp (b_18, 4), 0);

  /* Line: 33        : MULTIPLY           : calculate-cbf.cbl */
#line 33 "calculate-cbf.cbl"
  module->statement = STMT_MULTIPLY;
#line 212 "calculate-cbf.c"
  module->module_stmt = 0x00100021;
  cob_decimal_set_llint (d_0, 3LL);
  cob_check_numeric (COB_SET_DATA (f_25, b_21 + 3), "ID-D4");
  cob_decimal_set_field (d_1, COB_SET_DATA (f_25, b_21 + 3));
  cob_decimal_mul (d_0, d_1);
  cob_decimal_get_field (d_0, &f_18, 0);

  /* Line: 34        : ADD                : calculate-cbf.cbl */
#line 34 "calculate-cbf.cbl"
  module->statement = STMT_ADD;
#line 223 "calculate-cbf.c"
  module->module_stmt = 0x00100022;
  cob_check_numeric (&f_18, "TMP");
  cob_check_numeric (&f_17, "SUMA-DIGITOS");
  cob_add_int (&f_17, cob_get_numdisp (b_18, 4), 0);

  /* Line: 36        : MULTIPLY           : calculate-cbf.cbl */
#line 36 "calculate-cbf.cbl"
  module->statement = STMT_MULTIPLY;
#line 232 "calculate-cbf.c"
  module->module_stmt = 0x00100024;
  cob_decimal_set_llint (d_0, 2LL);
  cob_check_numeric (COB_SET_DATA (f_26, b_21 + 4), "ID-D5");
  cob_decimal_set_field (d_1, COB_SET_DATA (f_26, b_21 + 4));
  cob_decimal_mul (d_0, d_1);
  cob_decimal_get_field (d_0, &f_18, 0);

  /* Line: 37        : ADD                : calculate-cbf.cbl */
#line 37 "calculate-cbf.cbl"
  module->statement = STMT_ADD;
#line 243 "calculate-cbf.c"
  module->module_stmt = 0x00100025;
  cob_check_numeric (&f_18, "TMP");
  cob_check_numeric (&f_17, "SUMA-DIGITOS");
  cob_add_int (&f_17, cob_get_numdisp (b_18, 4), 0);

  /* Line: 39        : DIVIDE             : calculate-cbf.cbl */
#line 39 "calculate-cbf.cbl"
  module->statement = STMT_DIVIDE;
#line 252 "calculate-cbf.c"
  module->module_stmt = 0x00100027;
  cob_div_quotient (&f_17, (cob_field *)&c_1, &f_18, 0);
  cob_div_remainder (&f_19, 0);

  /* Line: 41        : COMPUTE            : calculate-cbf.cbl */
#line 41 "calculate-cbf.cbl"
  module->statement = STMT_COMPUTE;
#line 260 "calculate-cbf.c"
  module->module_stmt = 0x00100029;
  cob_decimal_set_llint (d_0, 11LL);
  cob_check_numeric (&f_19, "RESTO");
  cob_decimal_set_field (d_1, &f_19);
  cob_decimal_sub (d_0, d_1);
  cob_decimal_get_field (d_0, &f_20, 0);

  /* Line: 42        : IF                 : calculate-cbf.cbl */
#line 42 "calculate-cbf.cbl"
  module->statement = STMT_IF;
#line 271 "calculate-cbf.c"
  module->module_stmt = 0x0010002A;
  /* IF has code omitted */

  /* Line: 46        : MOVE               : calculate-cbf.cbl */
#line 46 "calculate-cbf.cbl"
  module->statement = STMT_MOVE;
#line 278 "calculate-cbf.c"
  module->module_stmt = 0x0010002E;
  cob_check_numeric (COB_SET_DATA (f_22, b_21), "ID-D1");
  *(b_27 + 0LL) = *(b_21);

  /* Line: 47        : MOVE               : calculate-cbf.cbl */
#line 47 "calculate-cbf.cbl"
  module->statement = STMT_MOVE;
#line 286 "calculate-cbf.c"
  module->module_stmt = 0x0010002F;
  cob_check_numeric (COB_SET_DATA (f_23, b_21 + 1), "ID-D2");
  *(b_27 + 1LL) = *(b_21 + 1);

  /* Line: 48        : MOVE               : calculate-cbf.cbl */
#line 48 "calculate-cbf.cbl"
  module->statement = STMT_MOVE;
#line 294 "calculate-cbf.c"
  module->module_stmt = 0x00100030;
  cob_check_numeric (COB_SET_DATA (f_24, b_21 + 2), "ID-D3");
  *(b_27 + 2LL) = *(b_21 + 2);

  /* Line: 49        : MOVE               : calculate-cbf.cbl */
#line 49 "calculate-cbf.cbl"
  module->statement = STMT_MOVE;
#line 302 "calculate-cbf.c"
  module->module_stmt = 0x00100031;
  cob_check_numeric (COB_SET_DATA (f_25, b_21 + 3), "ID-D4");
  *(b_27 + 3LL) = *(b_21 + 3);

  /* Line: 50        : MOVE               : calculate-cbf.cbl */
#line 50 "calculate-cbf.cbl"
  module->statement = STMT_MOVE;
#line 310 "calculate-cbf.c"
  module->module_stmt = 0x00100032;
  cob_check_numeric (COB_SET_DATA (f_26, b_21 + 4), "ID-D5");
  *(b_27 + 4LL) = *(b_21 + 4);

  /* Line: 51        : MOVE               : calculate-cbf.cbl */
#line 51 "calculate-cbf.cbl"
  module->statement = STMT_MOVE;
#line 318 "calculate-cbf.c"
  module->module_stmt = 0x00100033;
  cob_check_numeric (&f_20, "DV");
  *(b_27 + 5LL) = *(b_20);

  /* Line: 53        : GOBACK             : calculate-cbf.cbl */
#line 53 "calculate-cbf.cbl"
  module->statement = STMT_GOBACK;
#line 326 "calculate-cbf.c"
  module->module_stmt = 0x00100035;
  goto exit_program;

  /* Line: 54        : last source line                  :calculate-cbf.cbl */
#line 54 "calculate-cbf.cbl"
  module->module_stmt = 0x00100036;
#line 333 "calculate-cbf.c"
  cob_nop ();


  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  CALCULATE__CBF_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field SUMA-DIGITOS */
#line 5 "calculate-cbf.cbl"
  cob_nop ();
#line 385 "calculate-cbf.c"
  memset (b_17, 48, 4);

  /* initialize field TMP */
#line 6 "calculate-cbf.cbl"
  cob_nop ();
#line 391 "calculate-cbf.c"
  memset (b_18, (unsigned char)'0', 4);

  /* initialize field RESTO */
#line 7 "calculate-cbf.cbl"
  cob_nop ();
#line 397 "calculate-cbf.c"
  memset (b_19, (unsigned char)'0', 2);

  /* initialize field DV */
#line 8 "calculate-cbf.cbl"
  cob_nop ();
#line 403 "calculate-cbf.c"
  *(cob_u8_ptr)(b_20) = (unsigned char)'0';


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'CALCULATE-CBF' */

/* Initialize module structure for CALCULATE-CBF */
static void CALCULATE__CBF_module_init (cob_module *module)
{
  module->module_name = "CALCULATE-CBF";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())CALCULATE__CBF;
  module->module_cancel.funcptr = (void *(*)())CALCULATE__CBF_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 2;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

