/* Generated by           cobc 3.2.0 */
/* Generated from         calculate-cbf.cbl */
/* Generated at           Sep 08 2025 04:12:50 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\msys64\mingw64\bin\cobc.exe -x -I C:\msys64\home\lopez\COBOL\cajero-automatico\includes -g -o main.exe C:\msys64\home\lopez\COBOL\cajero-automatico\main.cbl calculate-cbf.cbl crear-cbf.cbl buscar-cliente.cbl guardar-cliente.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x10,   1,   0, 0x0000, NULL};
static const cob_field_attr a_2 =	{0x10,   4,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x10,   2,   0, 0x1000, NULL};
static const cob_field_attr a_4 =	{0x10,   2,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {2, (cob_u8_ptr)"11", &a_3};


#define cob_nop	if (!module) cob_nop


static int COB_INLINE COB_A_INLINE
cob_get_numdisp (const void *data, const int size)
{
	register const unsigned char	*p = (const unsigned char *)data;
	register int	n;
	register int	val = 0;
	for (n = 0; n < val; ++n, ++p) {
		if (*p > '0' && *p <= '9')
			break;
	}
	for (n = 0; n < size; ++n, ++p) {
		val = (val * 10)
		    + (*p & 0x0F);
	}
	return val;
}

