/* Generated by           cobc 3.2.0 */
/* Generated from         crear-cbf.cbl */
/* Generated at           Sep 08 2025 04:12:51 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\msys64\mingw64\bin\cobc.exe -x -I C:\msys64\home\lopez\COBOL\cajero-automatico\includes -g -o main.exe C:\msys64\home\lopez\COBOL\cajero-automatico\main.cbl calculate-cbf.cbl crear-cbf.cbl buscar-cliente.cbl guardar-cliente.cbl */

/* Program local variables for 'CREAR-CBF' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* File CSV-FILE */
static cob_file		*h_CSV_FILE = NULL;
static unsigned char	h_CSV_FILE_status[4];

/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */

/* Last USING parameters for possible later lookup */
static unsigned char	*last_b_30;
static unsigned char	*last_b_36;

/* Call pointers */
static cob_call_union	call_CALCULATE__CBF;
static cob_call_union	call_BUSCAR__CLIENTE;
static cob_call_union	call_GUARDAR__CLIENTE;

/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[2];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_22[116] __attribute__((aligned));	/* CSV-FILE Record */
static cob_u8_t	b_23[1] __attribute__((aligned));	/* EOF-FLAG */
static cob_u8_t	b_24[6] __attribute__((aligned));	/* ID-CUENTA-STR */
static cob_u8_t	b_25[2] __attribute__((aligned));	/* FILE-STATUS */

/* End of local data storage */


/* Fields (local) */
static cob_field f_17	= {116, b_22, &a_4};	/* CSV-REGISTRO */
static cob_field f_22	= {116, b_22, &a_1};	/* CSV-FILE Record */
static cob_field f_24	= {6, b_24, &a_1};	/* ID-CUENTA-STR */
static cob_field f_30	= {5, NULL, &a_4};	/* ID-CUENTA */
static cob_field f_31	= {1, NULL, &a_3};	/* ID-D1 */
static cob_field f_32	= {1, NULL, &a_3};	/* ID-D2 */
static cob_field f_33	= {1, NULL, &a_3};	/* ID-D3 */
static cob_field f_34	= {1, NULL, &a_3};	/* ID-D4 */
static cob_field f_35	= {1, NULL, &a_3};	/* ID-D5 */
static cob_field f_36	= {6, NULL, &a_1};	/* CLAVE-BANCARIA */

/* End of fields */

