/* Generated by           cobc 3.2.0 */
/* Generated from         crear-cbf.cbl */
/* Generated at           Sep 08 2025 04:12:51 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\msys64\mingw64\bin\cobc.exe -x -I C:\msys64\home\lopez\COBOL\cajero-automatico\includes -g -o main.exe C:\msys64\home\lopez\COBOL\cajero-automatico\main.cbl calculate-cbf.cbl crear-cbf.cbl buscar-cliente.cbl guardar-cliente.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"crear-cbf.cbl"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 08 2025 04:12:51"
#define  COB_MODULE_DATE		20250908
#define  COB_MODULE_TIME		41251

/* Global variables */
#include "crear-cbf.c.h"

/* Function prototypes */

COB_EXT_EXPORT int		CREAR__CBF (cob_u8_t *, cob_u8_t *);
static int		CREAR__CBF_ (const int, cob_u8_t *, cob_u8_t *);
static void		CREAR__CBF_module_init (cob_module *module);

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'CREAR-CBF' */

/* ENTRY 'CREAR__CBF' */

int
CREAR__CBF (cob_u8_t *b_30, cob_u8_t *b_36)
{
  cob_u8_t *cob_parm_30 = NULL;	/* linkage for ID-CUENTA */
  cob_u8_t *cob_parm_36 = NULL;	/* linkage for CLAVE-BANCARIA */

  /* Get current number of call parameters,
     if the parameter count is unknown, set it to all */
  if (cob_get_global_ptr ()->cob_current_module) {
  	cob_call_params = cob_get_global_ptr ()->cob_call_params;
  } else {
  	cob_call_params = 2;
  }

  /* Set the parameter list */
  if (cob_call_params > 0) {
    cob_parm_30 = b_30;
  }
  if (cob_call_params > 1) {
    cob_parm_36 = b_36;
  }

  return CREAR__CBF_ (0, cob_parm_30, cob_parm_36);
}

static int
CREAR__CBF_ (const int entry, cob_u8_t *b_30, cob_u8_t *b_36)
{
  /* Program local variables */
  #include "crear-cbf.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Store last parameters for possible later lookup */
  last_b_30 = b_30;
  last_b_36 = b_36;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 1         : Entry     CREAR-CBF               : includes\open.cbl */
  l_2:;
#line 1 "includes\\open.cbl"
  ENTRY_CREAR__CBF:	cob_nop ();
#line 120 "crear-cbf.c"

  /* Line: 1         : OPEN               : includes\open.cbl */
#line 1 "includes\\open.cbl"
  cob_nop ();
#line 125 "crear-cbf.c"
  cob_open (h_CSV_FILE, COB_OPEN_INPUT, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_5;
    goto l_1;
    l_5:
    frame_ptr--;
  }

  /* Line: 40        : PERFORM            : crear-cbf.cbl */
#line 40 "crear-cbf.cbl"
  cob_nop ();
#line 143 "crear-cbf.c"
  for (;;)
  {
    /* Line: 40        : UNTIL              : crear-cbf.cbl */
#line 40 "crear-cbf.cbl"
    cob_nop ();
#line 149 "crear-cbf.c"
    if (((int)cob_cmp_numdisp (b_23, 1, 1LL, 0) == 0))
      break;

    /* Line: 41        : READ               : crear-cbf.cbl */
#line 41 "crear-cbf.cbl"
    cob_nop ();
#line 156 "crear-cbf.c"
    cob_read_next (h_CSV_FILE, NULL, 1);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      if (cob_glob_ptr->cob_exception_code == 0x0501)
      {

        /* Line: 42        : MOVE               : crear-cbf.cbl */
#line 42 "crear-cbf.cbl"
        cob_nop ();
#line 166 "crear-cbf.c"
        *(b_23) = 49;
      }
      else
      {
        /* USE PROCEDURE Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
        	cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_ptr = &&l_6;
        goto l_1;
        l_6:
        frame_ptr--;
      }
    }
    else
    {

      /* Line: 45        : MOVE               : crear-cbf.cbl */
#line 45 "crear-cbf.cbl"
      cob_nop ();
#line 188 "crear-cbf.c"
      memcpy (b_24, b_22 + 0LL, 6);

      /* Line: 46        : INSPECT            : crear-cbf.cbl */
#line 46 "crear-cbf.cbl"
      cob_nop ();
#line 194 "crear-cbf.c"
      cob_inspect_init (&f_24, 1);
      cob_inspect_start ();
      cob_inspect_all ((cob_field *)&c_1, (cob_field *)&c_2);
      cob_inspect_finish ();

      /* Line: 47        : MOVE               : crear-cbf.cbl */
#line 47 "crear-cbf.cbl"
      cob_nop ();
#line 203 "crear-cbf.c"
      cob_move (COB_SET_FLD (f0, 1, b_24 + 0LL, &a_1), COB_SET_DATA (f_31, b_30));

      /* Line: 48        : MOVE               : crear-cbf.cbl */
#line 48 "crear-cbf.cbl"
      cob_nop ();
#line 209 "crear-cbf.c"
      cob_move (COB_SET_FLD (f0, 1, b_24 + 1LL, &a_1), COB_SET_DATA (f_32, b_30 + 1));

      /* Line: 49        : MOVE               : crear-cbf.cbl */
#line 49 "crear-cbf.cbl"
      cob_nop ();
#line 215 "crear-cbf.c"
      cob_move (COB_SET_FLD (f0, 1, b_24 + 2LL, &a_1), COB_SET_DATA (f_33, b_30 + 2));

      /* Line: 50        : MOVE               : crear-cbf.cbl */
#line 50 "crear-cbf.cbl"
      cob_nop ();
#line 221 "crear-cbf.c"
      cob_move (COB_SET_FLD (f0, 1, b_24 + 3LL, &a_1), COB_SET_DATA (f_34, b_30 + 3));

      /* Line: 51        : MOVE               : crear-cbf.cbl */
#line 51 "crear-cbf.cbl"
      cob_nop ();
#line 227 "crear-cbf.c"
      cob_move (COB_SET_FLD (f0, 1, b_24 + 4LL, &a_1), COB_SET_DATA (f_35, b_30 + 4));

      /* Line: 54        : CALL               : crear-cbf.cbl */
#line 54 "crear-cbf.cbl"
      cob_nop ();
#line 233 "crear-cbf.c"
      cob_procedure_params[0] = COB_SET_DATA (f_30, b_30);
      cob_procedure_params[1] = COB_SET_DATA (f_36, b_36);
      cob_glob_ptr->cob_call_params = 2;
      cob_glob_ptr->cob_stmt_exception = 0;
      if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
            if (unlikely(call_CALCULATE__CBF.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
      {
        call_CALCULATE__CBF.funcvoid = cob_resolve_cobol ("CALCULATE-CBF", 0, 1);
      }
      b_2 = ((int (*)(void *, void *))call_CALCULATE__CBF.funcint) (b_30, b_36);

      /* Line: 55        : DISPLAY            : crear-cbf.cbl */
#line 55 "crear-cbf.cbl"
      cob_nop ();
#line 248 "crear-cbf.c"
      cob_display (0, 1, 4, &c_3, &f_24, &c_4, COB_SET_DATA (f_36, b_36));

      /* Line: 58        : CALL               : crear-cbf.cbl */
#line 58 "crear-cbf.cbl"
      cob_nop ();
#line 254 "crear-cbf.c"
      cob_procedure_params[0] = COB_SET_DATA (f_36, b_36);
      cob_procedure_params[1] = &f_24;
      cob_glob_ptr->cob_call_params = 2;
      cob_glob_ptr->cob_stmt_exception = 0;
      if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
            if (unlikely(call_BUSCAR__CLIENTE.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
      {
        call_BUSCAR__CLIENTE.funcvoid = cob_resolve_cobol ("BUSCAR-CLIENTE", 0, 1);
      }
      b_2 = ((int (*)(void *, void *))call_BUSCAR__CLIENTE.funcint) (b_36, b_24);

      /* Line: 60        : IF                 : crear-cbf.cbl */
#line 60 "crear-cbf.cbl"
      cob_nop ();
#line 269 "crear-cbf.c"
      if (((int)memcmp (b_24, (cob_u8_ptr)"000000", 6) == 0))
      {

        /* Line: 61        : CALL               : crear-cbf.cbl */
#line 61 "crear-cbf.cbl"
        cob_nop ();
#line 276 "crear-cbf.c"
        cob_procedure_params[0] = COB_SET_DATA (f_36, b_36);
        cob_procedure_params[1] = &f_17;
        cob_glob_ptr->cob_call_params = 2;
        cob_glob_ptr->cob_stmt_exception = 0;
        if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
                if (unlikely(call_GUARDAR__CLIENTE.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
        {
          call_GUARDAR__CLIENTE.funcvoid = cob_resolve_cobol ("GUARDAR-CLIENTE", 0, 1);
        }
        b_2 = ((int (*)(void *, void *))call_GUARDAR__CLIENTE.funcint) (b_36, b_22);
      }
      else
      {
        /* ELSE */

        /* Line: 64        : DISPLAY            : crear-cbf.cbl */
#line 64 "crear-cbf.cbl"
        cob_nop ();
#line 295 "crear-cbf.c"
        cob_display (0, 1, 1, &c_5);
      }
    }
  }

  /* Line: 1         : CLOSE              : includes\close.cbl */
#line 1 "includes\\close.cbl"
  cob_nop ();
#line 304 "crear-cbf.c"
  cob_close (h_CSV_FILE, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_7;
    goto l_1;
    l_7:
    frame_ptr--;
  }

  /* Line: 2         : DISPLAY            : includes\close.cbl */
#line 2 "includes\\close.cbl"
  cob_nop ();
#line 322 "crear-cbf.c"
  cob_display (0, 1, 1, &c_6);

  /* Line: 70        : GOBACK             : crear-cbf.cbl */
#line 70 "crear-cbf.cbl"
  cob_nop ();
#line 328 "crear-cbf.c"
  goto exit_program;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : crear-cbf.cbl */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS))
  	cob_fatal_error (COB_FERROR_FILE);

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  CREAR__CBF_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field EOF-FLAG */
#line 19 "crear-cbf.cbl"
  cob_nop ();
#line 394 "crear-cbf.c"
  *(b_23) = 48;

  /* initialize field ID-CUENTA-STR */
#line 20 "crear-cbf.cbl"
  cob_nop ();
#line 400 "crear-cbf.c"
  memset (b_24, (unsigned char)' ', 6);

  /* initialize field FILE-STATUS */
#line 21 "crear-cbf.cbl"
  cob_nop ();
#line 406 "crear-cbf.c"
  memset (b_25, (unsigned char)' ', 2);


  /* File initialization for CSV-FILE */
  cob_file_malloc (&h_CSV_FILE, NULL, 0, 0);
  h_CSV_FILE->select_name = (const char *)"CSV-FILE";
  h_CSV_FILE->file_status = h_CSV_FILE_status;
  memset (h_CSV_FILE_status, '0', 2);
  h_CSV_FILE->assign = (cob_field *)&c_7;
  h_CSV_FILE->record = &f_22;
  h_CSV_FILE->variable_record = NULL;
  h_CSV_FILE->record_min = 0;
  h_CSV_FILE->record_max = 116;
  h_CSV_FILE->file = NULL;
  h_CSV_FILE->organization = 1;
  h_CSV_FILE->access_mode = 1;
  h_CSV_FILE->lock_mode = 0;
  h_CSV_FILE->open_mode = 0;
  h_CSV_FILE->flag_optional = 0;
  h_CSV_FILE->flag_line_adv = 0;
  h_CSV_FILE->flag_select_features = 0;

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  if (h_CSV_FILE->open_mode != COB_OPEN_CLOSED)
  	cob_close (h_CSV_FILE, NULL, COB_CLOSE_NORMAL, 1);
  cob_file_free (&h_CSV_FILE,NULL);
  call_GUARDAR__CLIENTE.funcvoid = NULL;
  call_BUSCAR__CLIENTE.funcvoid = NULL;
  call_CALCULATE__CBF.funcvoid = NULL;
  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'CREAR-CBF' */

/* Initialize module structure for CREAR-CBF */
static void CREAR__CBF_module_init (cob_module *module)
{
  module->module_name = "CREAR-CBF";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())CREAR__CBF;
  module->module_cancel.funcptr = (void *(*)())CREAR__CBF_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 2;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

