/* Generated by           cobc 3.2.0 */
/* Generated from         guardar-cliente.cbl */
/* Generated at           Sep 09 2025 20:38:37 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\msys64\mingw64\bin\cobc.exe -x -std=default -g -I ./copybooks -debug C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl buscar-cliente.cbl calculate-cbf.cbl crear-cbf.cbl guardar-cliente.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"guardar-cliente.cbl"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 09 2025 20:38:37"
#define  COB_MODULE_DATE		20250909
#define  COB_MODULE_TIME		203837

/* Global variables */
#include "guardar-cliente.c.h"

/* Function prototypes */

COB_EXT_EXPORT int		GUARDAR__CLIENTE (cob_u8_t *, cob_u8_t *);
static int		GUARDAR__CLIENTE_ (const int, cob_u8_t *, cob_u8_t *);
static void		GUARDAR__CLIENTE_module_init (cob_module *module);

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'GUARDAR-CLIENTE' */

/* ENTRY 'GUARDAR__CLIENTE' */

int
GUARDAR__CLIENTE (cob_u8_t *b_28, cob_u8_t *b_29)
{
  cob_u8_t *cob_parm_28 = NULL;	/* linkage for CLAVE-BANCARIA */
  cob_u8_t *cob_parm_29 = NULL;	/* linkage for CSV-REGISTRO */

  /* Get current number of call parameters,
     if the parameter count is unknown, set it to all */
  if (cob_get_global_ptr ()->cob_current_module) {
  	cob_call_params = cob_get_global_ptr ()->cob_call_params;
  } else {
  	cob_call_params = 2;
  }

  /* Set the parameter list */
  if (cob_call_params > 0) {
    cob_parm_28 = b_28;
  }
  if (cob_call_params > 1) {
    cob_parm_29 = b_29;
  }

#line 37 "guardar-cliente.cbl"
  if (cob_check_linkage_size ("GUARDAR__CLIENTE", "CLAVE-BANCARIA", 1, 0, 6, st_source_files, 1048613)) {
#line 65 "guardar-cliente.c"
  	return -1;
  }
#line 37 "guardar-cliente.cbl"
  if (cob_check_linkage_size ("GUARDAR__CLIENTE", "CSV-REGISTRO", 2, 0, 116, st_source_files, 1048613)) {
#line 70 "guardar-cliente.c"
  	return -1;
  }
  return GUARDAR__CLIENTE_ (0, cob_parm_28, cob_parm_29);
}

static int
GUARDAR__CLIENTE_ (const int entry, cob_u8_t *b_28, cob_u8_t *b_29)
{
  /* Program local variables */
  #include "guardar-cliente.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;
  module->frame_ptr = frame_stack;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Store last parameters for possible later lookup */
  last_b_28 = b_28;
  last_b_29 = b_29;

  /* Entry dispatch */
  module->frame_ptr->section_name = "";
  module->frame_ptr->paragraph_name = "GUARDAR-CLIENTE";
  module->frame_ptr->module_stmt = 0x00100026;
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 38        : Entry     GUARDAR-CLIENTE         : guardar-cliente.cbl */
  l_2:;
#line 38 "guardar-cliente.cbl"
  ENTRY_GUARDAR__CLIENTE:	module->statement = STMT_ENTRY;
#line 134 "guardar-cliente.c"
  module->module_stmt = 0x00100026;
  module->section_name = NULL;
  module->paragraph_name = NULL;

  /* Line: 38        : Paragraph MAIN-GUARDAR-CLIENTE    : guardar-cliente.cbl */
#line 38 "guardar-cliente.cbl"
  PARAGRAPH_MAIN__GUARDAR__CLIENTE_l_4:	module->statement = STMT_ENTRY;
#line 142 "guardar-cliente.c"
  module->paragraph_name = st_1;

  /* Line: 1         : OPEN               : includes\open-file-client.cbl */
#line 1 "includes\\open-file-client.cbl"
  module->statement = STMT_OPEN;
#line 148 "guardar-cliente.c"
  module->module_stmt = 0x00200001;
  cob_open (h_CUENTAS_FILE, COB_OPEN_I_O, 0, &f_23);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_5;
    goto l_1;
    l_5:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;
  }

  /* Line: 2         : IF                 : includes\open-file-client.cbl */
#line 2 "includes\\open-file-client.cbl"
  module->statement = STMT_IF;
#line 175 "guardar-cliente.c"
  module->module_stmt = 0x00200002;
  if (((int)memcmp (b_23, (cob_u8_ptr)"35", 2) == 0))
  {

    /* Line: 3         : DISPLAY            : includes\open-file-client.cbl */
#line 3 "includes\\open-file-client.cbl"
    module->statement = STMT_DISPLAY;
#line 183 "guardar-cliente.c"
    module->module_stmt = 0x00200003;
    cob_display (0, 1, 1, &c_1);

    /* Line: 4         : OPEN               : includes\open-file-client.cbl */
#line 4 "includes\\open-file-client.cbl"
    module->statement = STMT_OPEN;
#line 190 "guardar-cliente.c"
    module->module_stmt = 0x00200004;
    cob_open (h_CUENTAS_FILE, COB_OPEN_OUTPUT, 0, &f_23);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* USE PROCEDURE Default Error Handler */
      frame_ptr++;
      frame_ptr->module_stmt = module->module_stmt;
      frame_ptr->section_name = module->section_name;
      frame_ptr->paragraph_name = module->paragraph_name;
      module->frame_ptr = frame_ptr;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_6;
      goto l_1;
      l_6:
      frame_ptr--;
      module->module_stmt = module->frame_ptr->module_stmt;
      module->section_name = module->frame_ptr->section_name;
      module->paragraph_name = module->frame_ptr->paragraph_name;
      module->frame_ptr = frame_ptr;
    }

    /* Line: 5         : CLOSE              : includes\open-file-client.cbl */
#line 5 "includes\\open-file-client.cbl"
    module->statement = STMT_CLOSE;
#line 217 "guardar-cliente.c"
    module->module_stmt = 0x00200005;
    cob_close (h_CUENTAS_FILE, &f_23, 0, 0);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* USE PROCEDURE Default Error Handler */
      frame_ptr++;
      frame_ptr->module_stmt = module->module_stmt;
      frame_ptr->section_name = module->section_name;
      frame_ptr->paragraph_name = module->paragraph_name;
      module->frame_ptr = frame_ptr;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_7;
      goto l_1;
      l_7:
      frame_ptr--;
      module->module_stmt = module->frame_ptr->module_stmt;
      module->section_name = module->frame_ptr->section_name;
      module->paragraph_name = module->frame_ptr->paragraph_name;
      module->frame_ptr = frame_ptr;
    }

    /* Line: 6         : OPEN               : includes\open-file-client.cbl */
#line 6 "includes\\open-file-client.cbl"
    module->statement = STMT_OPEN;
#line 244 "guardar-cliente.c"
    module->module_stmt = 0x00200006;
    cob_open (h_CUENTAS_FILE, COB_OPEN_I_O, 0, &f_23);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* USE PROCEDURE Default Error Handler */
      frame_ptr++;
      frame_ptr->module_stmt = module->module_stmt;
      frame_ptr->section_name = module->section_name;
      frame_ptr->paragraph_name = module->paragraph_name;
      module->frame_ptr = frame_ptr;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_8;
      goto l_1;
      l_8:
      frame_ptr--;
      module->module_stmt = module->frame_ptr->module_stmt;
      module->section_name = module->frame_ptr->section_name;
      module->paragraph_name = module->frame_ptr->paragraph_name;
      module->frame_ptr = frame_ptr;
    }

    /* Line: 7         : IF                 : includes\open-file-client.cbl */
#line 7 "includes\\open-file-client.cbl"
    module->statement = STMT_IF;
#line 271 "guardar-cliente.c"
    module->module_stmt = 0x00200007;
    if (!((int)memcmp (b_23, (cob_u8_ptr)"00", 2) == 0))
    {

      /* Line: 8         : DISPLAY            : includes\open-file-client.cbl */
#line 8 "includes\\open-file-client.cbl"
      module->statement = STMT_DISPLAY;
#line 279 "guardar-cliente.c"
      module->module_stmt = 0x00200008;
      cob_display (0, 1, 1, &c_2);

      /* Line: 9         : STOP RUN           : includes\open-file-client.cbl */
#line 9 "includes\\open-file-client.cbl"
      module->statement = STMT_STOP_RUN;
#line 286 "guardar-cliente.c"
      module->module_stmt = 0x00200009;
      cob_stop_run (b_2);
    }
  }

  /* Line: 41        : MOVE               : guardar-cliente.cbl */
#line 41 "guardar-cliente.cbl"
  module->statement = STMT_MOVE;
#line 295 "guardar-cliente.c"
  module->module_stmt = 0x00100029;
  cob_check_numeric (COB_SET_DATA (f_28, b_28), "CLAVE-BANCARIA");
  memmove (b_22, b_28, 6);

  /* Line: 42        : MOVE               : guardar-cliente.cbl */
#line 42 "guardar-cliente.cbl"
  module->statement = STMT_MOVE;
#line 303 "guardar-cliente.c"
  module->module_stmt = 0x0010002A;
  memmove (b_22 + 6, b_29 + 6, 30);

  /* Line: 43        : MOVE               : guardar-cliente.cbl */
#line 43 "guardar-cliente.cbl"
  module->statement = STMT_MOVE;
#line 310 "guardar-cliente.c"
  module->module_stmt = 0x0010002B;
  memmove (b_22 + 36, b_29 + 36, 30);

  /* Line: 44        : MOVE               : guardar-cliente.cbl */
#line 44 "guardar-cliente.cbl"
  module->statement = STMT_MOVE;
#line 317 "guardar-cliente.c"
  module->module_stmt = 0x0010002C;
  memmove (b_22 + 66, b_29 + 66, 50);

  /* Line: 46        : WRITE              : guardar-cliente.cbl */
#line 46 "guardar-cliente.cbl"
  module->statement = STMT_WRITE;
#line 324 "guardar-cliente.c"
  module->module_stmt = 0x0010002E;
  cob_write (h_CUENTAS_FILE, &f_17, 0, &f_23, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    if (cob_glob_ptr->cob_exception_code == 0x0506)
    {

      /* Line: 48        : IF                 : guardar-cliente.cbl */
#line 48 "guardar-cliente.cbl"
      module->statement = STMT_IF;
#line 335 "guardar-cliente.c"
      module->module_stmt = 0x00100030;
      if (((int)memcmp (b_23, (cob_u8_ptr)"22", 2) == 0))
      {

        /* Line: 49        : DISPLAY            : guardar-cliente.cbl */
#line 49 "guardar-cliente.cbl"
        module->statement = STMT_DISPLAY;
#line 343 "guardar-cliente.c"
        module->module_stmt = 0x00100031;
        cob_display (0, 1, 2, &c_3, COB_SET_DATA (f_28, b_28));
      }
      else
      {
        /* ELSE */

        /* Line: 52        : DISPLAY            : guardar-cliente.cbl */
#line 52 "guardar-cliente.cbl"
        module->statement = STMT_DISPLAY;
#line 354 "guardar-cliente.c"
        module->module_stmt = 0x00100034;
        cob_display (0, 1, 2, &c_4, &f_23);
      }
    }
    else
    {
      /* USE PROCEDURE Default Error Handler */
      frame_ptr++;
      frame_ptr->module_stmt = module->module_stmt;
      frame_ptr->section_name = module->section_name;
      frame_ptr->paragraph_name = module->paragraph_name;
      module->frame_ptr = frame_ptr;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_9;
      goto l_1;
      l_9:
      frame_ptr--;
      module->module_stmt = module->frame_ptr->module_stmt;
      module->section_name = module->frame_ptr->section_name;
      module->paragraph_name = module->frame_ptr->paragraph_name;
      module->frame_ptr = frame_ptr;
    }
  }
  else
  {

    /* Line: 55        : DISPLAY            : guardar-cliente.cbl */
#line 55 "guardar-cliente.cbl"
    module->statement = STMT_DISPLAY;
#line 386 "guardar-cliente.c"
    module->module_stmt = 0x00100037;
    cob_display (0, 1, 1, &c_5);

    /* Line: 1         : CLOSE              : includes\close-file-client.cbl */
#line 1 "includes\\close-file-client.cbl"
    module->statement = STMT_CLOSE;
#line 393 "guardar-cliente.c"
    module->module_stmt = 0x00300001;
    cob_close (h_CUENTAS_FILE, &f_23, 0, 0);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* USE PROCEDURE Default Error Handler */
      frame_ptr++;
      frame_ptr->module_stmt = module->module_stmt;
      frame_ptr->section_name = module->section_name;
      frame_ptr->paragraph_name = module->paragraph_name;
      module->frame_ptr = frame_ptr;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_10;
      goto l_1;
      l_10:
      frame_ptr--;
      module->module_stmt = module->frame_ptr->module_stmt;
      module->section_name = module->frame_ptr->section_name;
      module->paragraph_name = module->frame_ptr->paragraph_name;
      module->frame_ptr = frame_ptr;
    }

    /* Line: 59        : GOBACK             : guardar-cliente.cbl */
#line 59 "guardar-cliente.cbl"
    module->statement = STMT_GOBACK;
#line 420 "guardar-cliente.c"
    module->module_stmt = 0x0010003B;
    goto exit_program;
  }

  /* Line: 60        : last source line                  :guardar-cliente.cbl */
#line 60 "guardar-cliente.cbl"
  module->module_stmt = 0x0010003C;
#line 428 "guardar-cliente.c"
  cob_nop ();


  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : guardar-cliente.cbl */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS))
  	cob_fatal_error (COB_FERROR_FILE);

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  GUARDAR__CLIENTE_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field FILE-STATUS */
#line 23 "guardar-cliente.cbl"
  cob_nop ();
#line 495 "guardar-cliente.c"
  memset (b_23, (unsigned char)' ', 2);


  /* File initialization for CUENTAS-FILE */
  cob_file_malloc (&h_CUENTAS_FILE, &k_CUENTAS_FILE, 1, 0);
  k_CUENTAS_FILE->field = &f_18;
  k_CUENTAS_FILE->tf_duplicates = 0;
  k_CUENTAS_FILE->offset = 0;
  h_CUENTAS_FILE->select_name = (const char *)"CUENTAS-FILE";
  h_CUENTAS_FILE->file_status = h_CUENTAS_FILE_status;
  memset (h_CUENTAS_FILE_status, '0', 2);
  h_CUENTAS_FILE->assign = (cob_field *)&c_6;
  h_CUENTAS_FILE->record = &f_22;
  h_CUENTAS_FILE->variable_record = NULL;
  h_CUENTAS_FILE->record_min = 116;
  h_CUENTAS_FILE->record_max = 116;
  h_CUENTAS_FILE->file = NULL;
  h_CUENTAS_FILE->organization = 3;
  h_CUENTAS_FILE->access_mode = 2;
  h_CUENTAS_FILE->lock_mode = 0;
  h_CUENTAS_FILE->open_mode = 0;
  h_CUENTAS_FILE->flag_optional = 0;
  h_CUENTAS_FILE->flag_line_adv = 0;
  h_CUENTAS_FILE->flag_select_features = 1;

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  if (h_CUENTAS_FILE->open_mode != COB_OPEN_CLOSED)
  	cob_close (h_CUENTAS_FILE, NULL, COB_CLOSE_NORMAL, 1);
  cob_file_free (&h_CUENTAS_FILE,&k_CUENTAS_FILE);
  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'GUARDAR-CLIENTE' */

/* Initialize module structure for GUARDAR-CLIENTE */
static void GUARDAR__CLIENTE_module_init (cob_module *module)
{
  module->module_name = "GUARDAR-CLIENTE";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())GUARDAR__CLIENTE;
  module->module_cancel.funcptr = (void *(*)())GUARDAR__CLIENTE_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 2;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

