/* Generated by           cobc 3.2.0 */
/* Generated from         guardar-cliente.cbl */
/* Generated at           Sep 09 2025 20:38:37 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\msys64\mingw64\bin\cobc.exe -x -std=default -g -I ./copybooks -debug C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl buscar-cliente.cbl calculate-cbf.cbl crear-cbf.cbl guardar-cliente.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_3 =	{0x10,   6,   0, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x01,   0,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {39, (cob_u8_ptr)"Archivo no existe, creando uno nuevo...", &a_2};
static const cob_field c_2	= {27, (cob_u8_ptr)"No se pudo abrir el archivo", &a_2};
static const cob_field c_3	= {32, (cob_u8_ptr)"Error: Clave Bancaria Existente!", &a_2};
static const cob_field c_4	= {18, (cob_u8_ptr)"Error al guardar; ", &a_2};
static const cob_field c_5	= {27, (cob_u8_ptr)"CLIENTE GUARDADO CON EXITO.", &a_2};
static const cob_field c_6	= {11, (cob_u8_ptr)"cuentas.dat", &a_2};


/* Strings */
static const char st_1[]	= "MAIN-GUARDAR-CLIENTE";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"guardar-cliente.cbl"
		,"includes\\open-file-client.cbl"
		,"includes\\close-file-client.cbl"};

#define cob_nop	if (!module) cob_nop

