/* Generated by           cobc 3.2.0 */
/* Generated from         guardar-cliente.cbl */
/* Generated at           Sep 09 2025 20:38:37 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\msys64\mingw64\bin\cobc.exe -x -std=default -g -I ./copybooks -debug C:\msys64\home\lopez\COBOL\cajero\altas\altas.cbl buscar-cliente.cbl calculate-cbf.cbl crear-cbf.cbl guardar-cliente.cbl */

/* Program local variables for 'GUARDAR-CLIENTE' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* File CUENTAS-FILE */
static cob_file_key	*k_CUENTAS_FILE = NULL;
static cob_file		*h_CUENTAS_FILE = NULL;
static unsigned char	h_CUENTAS_FILE_status[4];

/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */

/* Last USING parameters for possible later lookup */
static unsigned char	*last_b_28;
static unsigned char	*last_b_29;

/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame_ext	*frame_overflow;
struct cob_frame_ext	*frame_ptr;
struct cob_frame_ext	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_22[116] __attribute__((aligned));	/* CUENTAS-FILE Record */
static cob_u8_t	b_23[2] __attribute__((aligned));	/* FILE-STATUS */

/* End of local data storage */


/* Fields (local) */
static cob_field f_17	= {116, b_22, &a_4};	/* C-REGISTRO */
static cob_field f_18	= {6, b_22, &a_3};	/* CLI-CBF */
static cob_field f_22	= {116, b_22, &a_1};	/* CUENTAS-FILE Record */
static cob_field f_23	= {2, b_23, &a_1};	/* FILE-STATUS */
static cob_field f_28	= {6, NULL, &a_3};	/* CLAVE-BANCARIA */

/* End of fields */

